=== me-big-tuwien-ac-at/EAModelSet/schemas/ea-model.schema.json
{
  "$id": "https://me.big.tuwien.ac.at/EAModelSet/schemas/ea-model.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "EA Model Schema",
  "description": "A detailed representation of an EA Model including its elements, relationships, and views",
  "type": "object",
  "required": [
    "identifier",
    "archimateId",
    "name",
    "description",
    "formats",
    "source",
    "repository",
    "license",
    "sourceFile",
    "sourceFormat",
    "timestamp",
    "tags",
    "duplicates",
    "language",
    "elements",
    "relationships",
    "views"
  ],
  "properties": {
    "identifier": {
      "type": "string",
      "format": "uri",
      "description": "Unique URI identifier to access the model"
    },
    "archimateId": {
      "type": "string",
      "description": "ArchiMate ID from the source file of the model"
    },
    "name": {
      "type": "string",
      "description": "Name of the model"
    },
    "description": {
      "type": "string",
      "description": "Additional information about the model (e.g. description, purpose, scope)"
    },
    "formats": {
      "type": "array",
      "description": "Available, downloadable formats of the model",
      "items": {
        "type": "string",
        "enum": [ "JSON", "ARCHIMATE", "XML", "CSV", "PNG" ]
      }
    },
    "source": {
      "type": "string",
      "description": "Source where the model was downloaded from",
      "enum": [ "GitHub", "GenMyModel", "Other", "Unknown" ]
    },
    "repository": {
      "type": "string",
      "description": "Specific repository location of the source model"
    },
    "license": {
      "type": "string",
      "description": "License for the model"
    },
    "sourceFile": {
      "type": "string",
      "description": "Relative file path of the parsed model file"
    },
    "sourceFormat": {
      "type": "string",
      "description": "Source format of the original downloaded model",
      "enum": [ "ARCHIMATE", "XML" ]
    },
    "timestamp": {
      "type": "string",
      "format": "date-time"
    },
    "tags": {
      "type": "array",
      "description": "Additional tags to classify the model",
      "items": {
        "type": "string",
        "enum": [ "DUPLICATE", "WARNING" ]
      }
    },
    "duplicates": {
      "type": "array",
      "description": "Relative file path of detected duplicates (e.g. same ID)",
      "items": {
        "type": "string"
      }
    },
    "language": {
      "type": "string",
      "description": "Language of the model",
      "enum": [
        "aa", "ab", "ae", "af", "ak", "am", "an", "ar", "as", "av", "ay", "az", "ba", "be", "bg", "bi",
        "bm", "bn", "bo", "br", "bs", "ca", "ce", "ch", "co", "cr", "cs", "cu", "cv", "cy", "da", "de",
        "dv", "dz", "ee", "el", "en", "eo", "es", "et", "eu", "fa", "ff", "fi", "fj", "fo", "fr", "fy",
        "ga", "gd", "gl", "gn", "gu", "gv", "ha", "he", "hi", "ho", "hr", "ht", "hu", "hy", "hz", "ia",
        "id", "ie", "ig", "ii", "ik", "io", "is", "it", "iu", "ja", "jv", "ka", "kg", "ki", "kj", "kk",
        "kl", "km", "kn", "ko", "kr", "ks", "ku", "kv", "kw", "ky", "la", "lb", "lg", "li", "ln", "lo",
        "lt", "lu", "lv", "mg", "mh", "mi", "mk", "ml", "mn", "mr", "ms", "mt", "my", "na", "nb", "nd",
        "ne", "ng", "nl", "nn", "no", "nr", "nv", "ny", "oc", "oj", "om", "or", "os", "pa", "pi", "pl",
        "ps", "pt", "qu", "rm", "rn", "ro", "ru", "rw", "sa", "sc", "sd", "se", "sg", "sh", "si", "sk",
        "sl", "sm", "sn", "so", "sq", "sr", "ss", "st", "su", "sv", "sw", "ta", "te", "tg", "th", "ti",
        "tk", "tl", "tn", "to", "tr", "ts", "tt", "tw", "ty", "ug", "uk", "ur", "uz", "ve", "vi", "vo",
        "wa", "wo", "xh", "yi", "yo", "za", "zh", "zu"
      ]
    },
    "elements": {
      "type": "array",
      "items": { "$ref": "#/$defs/element" }
    },
    "relationships": {
      "type": "array",
      "items": { "$ref": "#/$defs/relationship" }
    },
    "views": {
      "type": "array",
      "items": { "$ref": "#/$defs/view" }
    }
  },
  "$defs": {
    "element": {
      "type": "object",
      "required": [ "id", "name", "type", "layer" ],
      "properties": {
        "id": {
          "type": "string",
          "description": "Unique identifier of the element"
        },
        "name": {
          "type": "string",
          "description": "Name of the element"
        },
        "type": {
          "type": "string",
          "description": "Type of the element"
        },
        "layer": {
          "type": "string",
          "description": "Layer of the element (computed through type)"
        }
      }
    },
    "relationship": {
      "type": "object",
      "required": [ "id", "sourceId", "targetId", "type" ],
      "properties": {
        "id": {
          "type": "string",
          "description": "Unique identifier of the element"
        },
        "sourceId": {
          "type": "string",
          "description": "ID of the source element"
        },
        "targetId": {
          "type": "string",
          "description": "ID of the target element"
        },
        "type": {
          "type": "string",
          "description": "Type of the element"
        }
      }
    },
    "view": {
      "type": "object",
      "required": [ "id", "name", "viewpoint"],
      "properties": {
        "id": {
          "type": "string",
          "description": "Unique identifier of the view"
        },
        "name": {
          "type": "string",
          "description": "Name of the element"
        },
        "viewpoint": {
          "type": "string",
          "description": "Associated viewpoint to the view (optional)"
        }
      }
    }
  }
}

=== me-big-tuwien-ac-at/EAModelSet/dataset/processed-models/id-7b3137ef-32e3-4089-a2d8-8a9a4a400eb4/model.json
{"identifier":"https://me.big.tuwien.ac.at/EAModelSet/id-7b3137ef-32e3-4089-a2d8-8a9a4a400eb4","archimateId":"id-7b3137ef-32e3-4089-a2d8-8a9a4a400eb4","name":"(new model)","description":"","formats":["XML","CSV","JSON","ARCHIMATE"],"source":"GitHub","repository":"","license":"","sourceFile":"raw-data/github/xml/archimatemodel.xml","sourceFormat":"XML","timestamp":"2023-07-06T09:29:17","tags":[],"duplicates":[],"language":"nn","elements":[{"id":"id-055970dc-7489-443f-85e6-436ba190cc38","name":"melding","type":"BusinessObject","layer":"business"},{"id":"id-3d5ae8f0-b30b-4780-9d36-339827385671","name":"aanhouding","type":"BusinessObject","layer":"business"},{"id":"id-f568e701-1146-4a2c-a8e7-77cd2ad829af","name":"aangifte","type":"BusinessObject","layer":"business"},{"id":"id-95e81a51-b106-4a01-aeb3-29bb88293da9","name":"incident","type":"BusinessObject","layer":"business"},{"id":"id-9fbc08e6-6035-4a64-be36-0e11ad5e7946","name":"meding registreren","type":"ApplicationService","layer":"application"},{"id":"id-0425f279-bdaa-40cd-a1e1-eccb2a82ba80","name":"aanhouding registreren","type":"ApplicationService","layer":"application"},{"id":"id-ea2858ea-59ae-40bd-b5eb-f6d47923ddf6","name":"aangifte registreren","type":"ApplicationService","layer":"application"},{"id":"id-292646f6-c701-47db-93d5-ad4339a356b1","name":"vastleggen incident","type":"ApplicationFunction","layer":"application"},{"id":"id-547ed4f8-afbd-4b88-915c-6d2ed5b0f94c","name":"vastleggen melding","type":"ApplicationFunction","layer":"application"},{"id":"id-fcffec28-6dfb-4cb1-ab64-2c123262ef8f","name":"vastleggen aanhouding","type":"ApplicationFunction","layer":"application"},{"id":"id-e34172e8-1814-4676-9ddd-cbb12f12602c","name":"vastleggen aangifte","type":"ApplicationFunction","layer":"application"},{"id":"id-9d5b6f84-e2a0-476d-9615-bcd3390da009","name":"bvh","type":"ApplicationComponent","layer":"application"},{"id":"id-c23bdacc-788e-4b6f-b678-59857a44f303","name":"opp","type":"ApplicationComponent","layer":"application"},{"id":"id-be27e1de-2d7d-4d54-9784-4f10d64baa43","name":"connect","type":"ApplicationComponent","layer":"application"},{"id":"id-093fb5fe-0547-46cd-bce4-ca8485a827a7","name":"gms","type":"ApplicationComponent","layer":"application"}],"relationships":[{"id":"id-04155091-83ba-427a-a36d-3aa1038e9a05","sourceId":"id-95e81a51-b106-4a01-aeb3-29bb88293da9","targetId":"id-055970dc-7489-443f-85e6-436ba190cc38","type":"Association"},{"id":"id-996cc489-6a0f-406e-80e6-5057b9e586b4","sourceId":"id-055970dc-7489-443f-85e6-436ba190cc38","targetId":"id-3d5ae8f0-b30b-4780-9d36-339827385671","type":"Association"},{"id":"id-2f33f539-628a-4e4b-a76d-792e8f52596d","sourceId":"id-3d5ae8f0-b30b-4780-9d36-339827385671","targetId":"id-f568e701-1146-4a2c-a8e7-77cd2ad829af","type":"Association"},{"id":"id-6acec0bb-904e-49a6-952a-dbd0857d958f","sourceId":"id-292646f6-c701-47db-93d5-ad4339a356b1","targetId":"id-9fbc08e6-6035-4a64-be36-0e11ad5e7946","type":"Realization"},{"id":"id-2b09036c-ff2e-419f-bfea-501367826f2a","sourceId":"id-547ed4f8-afbd-4b88-915c-6d2ed5b0f94c","targetId":"id-9fbc08e6-6035-4a64-be36-0e11ad5e7946","type":"Realization"},{"id":"id-1177768c-9728-447d-8af0-92ffc698f2bb","sourceId":"id-fcffec28-6dfb-4cb1-ab64-2c123262ef8f","targetId":"id-0425f279-bdaa-40cd-a1e1-eccb2a82ba80","type":"Realization"},{"id":"id-ae600ff3-878f-4570-8230-7f5ff9b8cea6","sourceId":"id-e34172e8-1814-4676-9ddd-cbb12f12602c","targetId":"id-ea2858ea-59ae-40bd-b5eb-f6d47923ddf6","type":"Realization"},{"id":"id-d27e47c6-329e-47f1-8d16-c2440c0865be","sourceId":"id-9d5b6f84-e2a0-476d-9615-bcd3390da009","targetId":"id-292646f6-c701-47db-93d5-ad4339a356b1","type":"Assignment"},{"id":"id-c4ff76a1-879a-48c6-85fb-1f834b820408","sourceId":"id-9d5b6f84-e2a0-476d-9615-bcd3390da009","targetId":"id-547ed4f8-afbd-4b88-915c-6d2ed5b0f94c","type":"Assignment"},{"id":"id-c16b56fa-daee-4d27-a82c-e3bce344ea3c","sourceId":"id-9d5b6f84-e2a0-476d-9615-bcd3390da009","targetId":"id-fcffec28-6dfb-4cb1-ab64-2c123262ef8f","type":"Assignment"},{"id":"id-b1294260-1df9-49cb-8171-600e47076f83","sourceId":"id-9d5b6f84-e2a0-476d-9615-bcd3390da009","targetId":"id-e34172e8-1814-4676-9ddd-cbb12f12602c","type":"Assignment"},{"id":"id-22c6eebf-01c7-49f3-9722-28e416d4c6b1","sourceId":"id-c23bdacc-788e-4b6f-b678-59857a44f303","targetId":"id-292646f6-c701-47db-93d5-ad4339a356b1","type":"Assignment"},{"id":"id-53480be0-f0e4-48d5-b615-d66e3dcbc028","sourceId":"id-c23bdacc-788e-4b6f-b678-59857a44f303","targetId":"id-547ed4f8-afbd-4b88-915c-6d2ed5b0f94c","type":"Assignment"},{"id":"id-d868ece0-5f92-4860-9d12-8e38a53a74d8","sourceId":"id-c23bdacc-788e-4b6f-b678-59857a44f303","targetId":"id-fcffec28-6dfb-4cb1-ab64-2c123262ef8f","type":"Assignment"},{"id":"id-ca6314fd-3efc-471a-b59c-afb80b2d46f5","sourceId":"id-c23bdacc-788e-4b6f-b678-59857a44f303","targetId":"id-e34172e8-1814-4676-9ddd-cbb12f12602c","type":"Assignment"},{"id":"id-349cf074-eca5-4959-9f4a-c72aed46553d","sourceId":"id-093fb5fe-0547-46cd-bce4-ca8485a827a7","targetId":"id-292646f6-c701-47db-93d5-ad4339a356b1","type":"Assignment"},{"id":"id-8800b5cc-784c-4d07-a611-050fcf206254","sourceId":"id-093fb5fe-0547-46cd-bce4-ca8485a827a7","targetId":"id-547ed4f8-afbd-4b88-915c-6d2ed5b0f94c","type":"Assignment"},{"id":"id-f401c5c5-b301-434e-a10e-56229d5f30ea","sourceId":"id-be27e1de-2d7d-4d54-9784-4f10d64baa43","targetId":"id-e34172e8-1814-4676-9ddd-cbb12f12602c","type":"Assignment"},{"id":"id-6e65e305-a33e-4989-aab6-ad8455511ac2","sourceId":"id-292646f6-c701-47db-93d5-ad4339a356b1","targetId":"id-95e81a51-b106-4a01-aeb3-29bb88293da9","type":"Access"},{"id":"id-8bbf091f-f30b-4948-bad2-b007585d8a1d","sourceId":"id-547ed4f8-afbd-4b88-915c-6d2ed5b0f94c","targetId":"id-055970dc-7489-443f-85e6-436ba190cc38","type":"Access"},{"id":"id-cf8d828e-e3c2-4cb2-9232-70931f8cf7f3","sourceId":"id-fcffec28-6dfb-4cb1-ab64-2c123262ef8f","targetId":"id-3d5ae8f0-b30b-4780-9d36-339827385671","type":"Access"},{"id":"id-a6fa546a-eeeb-45ed-ab24-9b274a6ef567","sourceId":"id-e34172e8-1814-4676-9ddd-cbb12f12602c","targetId":"id-f568e701-1146-4a2c-a8e7-77cd2ad829af","type":"Access"}],"views":[{"id":"id-4bf7a121-2ffd-42f0-b7b9-817073017c06","name":"Default View","viewpoint":""}]}

=== me-big-tuwien-ac-at/EAModelSet/vue-website/public/processed-models/_viXHACfbEeuxZMUIY-ihGw/model.json
{"identifier":"https://me.big.tuwien.ac.at/EAModelSet/_viXHACfbEeuxZMUIY-ihGw","archimateId":"_viXHACfbEeuxZMUIY-ihGw","name":"payments-arch1","description":"","formats":["XML","CSV","JSON","ARCHIMATE"],"source":"GenMyModel","repository":"","license":"","sourceFile":"raw-data/genmymodel/_vixhacfbeeuxzmuiy-ihgw.xml","sourceFormat":"XML","timestamp":"2023-07-06T10:01:17","tags":[],"duplicates":[],"language":"en","elements":[{"id":"_viZjjSfbEeuxZMUIY-ihGw","name":"WebForm Custom","type":"ApplicationService","layer":"application"},{"id":"_viZjjyfbEeuxZMUIY-ihGw","name":"WebHook Public Node","type":"ApplicationService","layer":"application"},{"id":"_viZjkSfbEeuxZMUIY-ihGw","name":"CloudPayments","type":"ApplicationService","layer":"application"},{"id":"_viZjkyfbEeuxZMUIY-ihGw","name":"others","type":"ApplicationService","layer":"application"},{"id":"_viZjlSfbEeuxZMUIY-ihGw","name":"Software","type":"SystemSoftware","layer":"technology"},{"id":"_viZjlyfbEeuxZMUIY-ihGw","name":"Collaboration","type":"BusinessCollaboration","layer":"business"},{"id":"_viZjmSfbEeuxZMUIY-ihGw","name":"Event Pub\\Sub Bus","type":"SystemSoftware","layer":"technology"},{"id":"_viZjmyfbEeuxZMUIY-ihGw","name":"App","type":"ApplicationService","layer":"application"},{"id":"_viZjnSfbEeuxZMUIY-ihGw","name":"General Store","type":"TechnologyCollaboration","layer":"technology"},{"id":"_viZjnyfbEeuxZMUIY-ihGw","name":"Internal Store","type":"TechnologyCollaboration","layer":"technology"},{"id":"_viZjoSfbEeuxZMUIY-ihGw","name":"Collaboration","type":"TechnologyCollaboration","layer":"technology"},{"id":"_viZjoyfbEeuxZMUIY-ihGw","name":"Core Service","type":"ApplicationService","layer":"application"},{"id":"_viZjpSfbEeuxZMUIY-ihGw","name":"Internal store","type":"TechnologyCollaboration","layer":"technology"},{"id":"_viZjpyfbEeuxZMUIY-ihGw","name":"Http Adapter service","type":"ApplicationService","layer":"application"},{"id":"_viZjqyfbEeuxZMUIY-ihGw","name":"Event Bus Adapter","type":"ApplicationService","layer":"application"},{"id":"_viZjrSfbEeuxZMUIY-ihGw","name":"Service","type":"ApplicationService","layer":"application"},{"id":"_viZjryfbEeuxZMUIY-ihGw","name":"Http Form Service","type":"ApplicationService","layer":"application"}],"relationships":[{"id":"_viZjsSfbEeuxZMUIY-ihGw","sourceId":"_viZjkSfbEeuxZMUIY-ihGw","targetId":"_viZjjyfbEeuxZMUIY-ihGw","type":"Serving"},{"id":"_viZjsyfbEeuxZMUIY-ihGw","sourceId":"_viZjjyfbEeuxZMUIY-ihGw","targetId":"_viZjpyfbEeuxZMUIY-ihGw","type":"Serving"},{"id":"_viZjtSfbEeuxZMUIY-ihGw","sourceId":"_viZjjSfbEeuxZMUIY-ihGw","targetId":"_viZjpyfbEeuxZMUIY-ihGw","type":"Serving"},{"id":"_viZjtyfbEeuxZMUIY-ihGw","sourceId":"_viZjpyfbEeuxZMUIY-ihGw","targetId":"_viZjoyfbEeuxZMUIY-ihGw","type":"Serving"},{"id":"_viZjuSfbEeuxZMUIY-ihGw","sourceId":"_viZjoyfbEeuxZMUIY-ihGw","targetId":"_viZjpyfbEeuxZMUIY-ihGw","type":"Serving"},{"id":"_viZjuyfbEeuxZMUIY-ihGw","sourceId":"_viZjpyfbEeuxZMUIY-ihGw","targetId":"_viZjjSfbEeuxZMUIY-ihGw","type":"Serving"},{"id":"_viZjvSfbEeuxZMUIY-ihGw","sourceId":"_viZjoyfbEeuxZMUIY-ihGw","targetId":"_viZjpSfbEeuxZMUIY-ihGw","type":"Serving"},{"id":"_viZjvyfbEeuxZMUIY-ihGw","sourceId":"_viZjpSfbEeuxZMUIY-ihGw","targetId":"_viZjoyfbEeuxZMUIY-ihGw","type":"Serving"},{"id":"_viZjwSfbEeuxZMUIY-ihGw","sourceId":"_viZjoyfbEeuxZMUIY-ihGw","targetId":"_viZjnSfbEeuxZMUIY-ihGw","type":"Serving"},{"id":"_viZjwyfbEeuxZMUIY-ihGw","sourceId":"_viZjnSfbEeuxZMUIY-ihGw","targetId":"_viZjoyfbEeuxZMUIY-ihGw","type":"Serving"},{"id":"_viZjzSfbEeuxZMUIY-ihGw","sourceId":"_viZjoyfbEeuxZMUIY-ihGw","targetId":"_viZjqyfbEeuxZMUIY-ihGw","type":"Serving"},{"id":"_viZjzyfbEeuxZMUIY-ihGw","sourceId":"_viZjqyfbEeuxZMUIY-ihGw","targetId":"_viZjmSfbEeuxZMUIY-ihGw","type":"Serving"},{"id":"_viZj0SfbEeuxZMUIY-ihGw","sourceId":"_viZjmSfbEeuxZMUIY-ihGw","targetId":"_viZjmyfbEeuxZMUIY-ihGw","type":"Serving"},{"id":"_viZj0yfbEeuxZMUIY-ihGw","sourceId":"_viZjoyfbEeuxZMUIY-ihGw","targetId":"_viZjkSfbEeuxZMUIY-ihGw","type":"Serving"},{"id":"_viZj1SfbEeuxZMUIY-ihGw","sourceId":"_viZjjSfbEeuxZMUIY-ihGw","targetId":"_viZjryfbEeuxZMUIY-ihGw","type":"Serving"},{"id":"_viZj1yfbEeuxZMUIY-ihGw","sourceId":"_viZjryfbEeuxZMUIY-ihGw","targetId":"_viZjoyfbEeuxZMUIY-ihGw","type":"Serving"}],"views":[{"id":"_viZjQCfbEeuxZMUIY-ihGw","name":"archimate-diagram","viewpoint":""}]}

=== me-big-tuwien-ac-at/EAModelSet/dataset/processed-models/_igZ_cKctEeqEM7mFKilpXw/model.json
{"identifier":"https://me.big.tuwien.ac.at/EAModelSet/_igZ_cKctEeqEM7mFKilpXw","archimateId":"_igZ_cKctEeqEM7mFKilpXw","name":"Belarus","description":"","formats":["XML","CSV","JSON","ARCHIMATE"],"source":"GenMyModel","repository":"","license":"","sourceFile":"raw-data/genmymodel/_igz_ckcteeqem7mfkilpxw.xml","sourceFormat":"XML","timestamp":"2023-07-06T10:01:17","tags":[],"duplicates":[],"language":"ru","elements":[{"id":"_hZvbkYlbEDikLZ5Pke9ylQ","name":"Запрос пропуска на территорию БелАЭС через ОРБ/ТАИ с приложением:1. Списка.2. Информации о запросе, направленном ранее (был коллективный)3. Официальных запросов на ШП, ШПНР","type":"BusinessFunction","layer":"business"},{"id":"_y_cuAIlbEDikLZ5Pke9ylQ","name":"Обращение в АСЭ для подготовки запроса с их стороны в СЭЗ РБ","type":"BusinessFunction","layer":"business"},{"id":"_3T2icYlbEDikLZ5Pke9ylQ","name":"Запрос в СЭЗ РБ за 7 дней от АСЭ с приложением:1. Списка2. Результатов 2-х тестов на вирус","type":"BusinessFunction","layer":"business"},{"id":"__KUvcYlbEDikLZ5Pke9ylQ","name":"Обработка запроса и решение через 5 дней","type":"BusinessFunction","layer":"business"},{"id":"_HcUa0IlcEDikLZ5Pke9ylQ","name":"Запрос пропуска на сотрудников РАДИКО","type":"BusinessFunction","layer":"business"},{"id":"_JAe8QYlcEDikLZ5Pke9ylQ","name":"ОРБ/ТАИ","type":"BusinessActor","layer":"business"},{"id":"_Z8LBUYlcEDikLZ5Pke9ylQ","name":"Получение справки о состоянии здоровья и 2 теста на COVID-19","type":"BusinessFunction","layer":"business"},{"id":"_fr2g8IlcEDikLZ5Pke9ylQ","name":"Обращение в АСЭ для формирования списка для передачи на границу","type":"BusinessFunction","layer":"business"},{"id":"_uLh2kYlcEDikLZ5Pke9ylQ","name":"Сдача 2-х дополнительных тестов","type":"BusinessFunction","layer":"business"},{"id":"_6OaZoIlcEDikLZ5Pke9ylQ","name":"РАДИКО","type":"BusinessCollaboration","layer":"business"},{"id":"_8XDhIIlcEDikLZ5Pke9ylQ","name":"Сотрудник","type":"BusinessActor","layer":"business"},{"id":"_AWB4IIldEDikLZ5Pke9ylQ","name":"АО ИК АСЭ","type":"BusinessRole","layer":"business"},{"id":"_C14lwYldEDikLZ5Pke9ylQ","name":"СЭЗ РБ","type":"BusinessRole","layer":"business"},{"id":"_E57hIYldEDikLZ5Pke9ylQ","name":"Выезд в день получения тестов и перемещение до границы со стороны РФ","type":"BusinessFunction","layer":"business"},{"id":"_HROIoIldEDikLZ5Pke9ylQ","name":"Сотрудник","type":"BusinessActor","layer":"business"},{"id":"_LYPBUYldEDikLZ5Pke9ylQ","name":"Перечение границы пешком","type":"BusinessFunction","layer":"business"},{"id":"_WSqHgYldEDikLZ5Pke9ylQ","name":"Запрос в ГК \"Росатом\" для разрешения пересечения границы (1 день)","type":"BusinessFunction","layer":"business"},{"id":"_Zoez0IldEDikLZ5Pke9ylQ","name":"Положительное решение по запросу и передача данных на границу (1 день)","type":"BusinessFunction","layer":"business"},{"id":"_eEJG0YldEDikLZ5Pke9ylQ","name":"АО ИК АСЭ","type":"BusinessRole","layer":"business"},{"id":"_fh6FUIldEDikLZ5Pke9ylQ","name":"ГК Росатом","type":"BusinessRole","layer":"business"},{"id":"_31rLMIldEDikLZ5Pke9ylQ","name":"Заселение в Санаторий \"Приозерный\" (предоставить тест сроком давности не старше 2-х дней)","type":"BusinessFunction","layer":"business"},{"id":"_AMrSYIleEDikLZ5Pke9ylQ","name":"Такси до санатория (или транспорт от АО ИК АСЭ)","type":"BusinessFunction","layer":"business"},{"id":"_Nqx2QYleEDikLZ5Pke9ylQ","name":"Выезд в санаторий и забор анализов в первый рабочий день после заселения","type":"BusinessFunction","layer":"business"},{"id":"_Sz5sMIleEDikLZ5Pke9ylQ","name":"СЭЗ РБ","type":"BusinessRole","layer":"business"},{"id":"_ZXWLEYleEDikLZ5Pke9ylQ","name":"Ожидание результатов тестов 3-4 дня","type":"BusinessFunction","layer":"business"},{"id":"_ca1xQYleEDikLZ5Pke9ylQ","name":"Сотрудник","type":"BusinessActor","layer":"business"},{"id":"_eX564IleEDikLZ5Pke9ylQ","name":"Выход на площадку","type":"BusinessFunction","layer":"business"},{"id":"_kZb_gYleEDikLZ5Pke9ylQ","name":"РАДИКО","type":"BusinessCollaboration","layer":"business"},{"id":"_w-A6YYleEDikLZ5Pke9ylQ","name":"Обработка запроса и решение (до 45 дней, если не было запроса ранее)","type":"BusinessFunction","layer":"business"},{"id":"_z68lkYleEDikLZ5Pke9ylQ","name":"Служба безопасности Белорусской АЭС","type":"BusinessRole","layer":"business"}],"relationships":[{"id":"_KKDzcYlcEDikLZ5Pke9ylQ","sourceId":"_JAe8QYlcEDikLZ5Pke9ylQ","targetId":"_HcUa0IlcEDikLZ5Pke9ylQ","type":"Association"},{"id":"_KfU40YlcEDikLZ5Pke9ylQ","sourceId":"_hZvbkYlbEDikLZ5Pke9ylQ","targetId":"_HcUa0IlcEDikLZ5Pke9ylQ","type":"Triggering"},{"id":"_Y4KmoYlcEDikLZ5Pke9ylQ","sourceId":"_3T2icYlbEDikLZ5Pke9ylQ","targetId":"__KUvcYlbEDikLZ5Pke9ylQ","type":"Triggering"},{"id":"_mIcw8YlcEDikLZ5Pke9ylQ","sourceId":"_y_cuAIlbEDikLZ5Pke9ylQ","targetId":"_3T2icYlbEDikLZ5Pke9ylQ","type":"Triggering"},{"id":"_0GNFQYlcEDikLZ5Pke9ylQ","sourceId":"_Z8LBUYlcEDikLZ5Pke9ylQ","targetId":"_y_cuAIlbEDikLZ5Pke9ylQ","type":"Triggering"},{"id":"_7VdhQYlcEDikLZ5Pke9ylQ","sourceId":"_6OaZoIlcEDikLZ5Pke9ylQ","targetId":"_fr2g8IlcEDikLZ5Pke9ylQ","type":"Association"},{"id":"_73nME4lcEDikLZ5Pke9ylQ","sourceId":"_6OaZoIlcEDikLZ5Pke9ylQ","targetId":"_y_cuAIlbEDikLZ5Pke9ylQ","type":"Association"},{"id":"_9ZICIYlcEDikLZ5Pke9ylQ","sourceId":"_Z8LBUYlcEDikLZ5Pke9ylQ","targetId":"_8XDhIIlcEDikLZ5Pke9ylQ","type":"Association"},{"id":"_B3S2kYldEDikLZ5Pke9ylQ","sourceId":"_AWB4IIldEDikLZ5Pke9ylQ","targetId":"_3T2icYlbEDikLZ5Pke9ylQ","type":"Association"},{"id":"_EAtaI4ldEDikLZ5Pke9ylQ","sourceId":"_C14lwYldEDikLZ5Pke9ylQ","targetId":"__KUvcYlbEDikLZ5Pke9ylQ","type":"Association"},{"id":"_IZNrcYldEDikLZ5Pke9ylQ","sourceId":"_uLh2kYlcEDikLZ5Pke9ylQ","targetId":"_HROIoIldEDikLZ5Pke9ylQ","type":"Association"},{"id":"_JEXhQYldEDikLZ5Pke9ylQ","sourceId":"_HROIoIldEDikLZ5Pke9ylQ","targetId":"_E57hIYldEDikLZ5Pke9ylQ","type":"Association"},{"id":"_JlClY4ldEDikLZ5Pke9ylQ","sourceId":"_uLh2kYlcEDikLZ5Pke9ylQ","targetId":"_E57hIYldEDikLZ5Pke9ylQ","type":"Triggering"},{"id":"_QbFQIYldEDikLZ5Pke9ylQ","sourceId":"_3T2icYlbEDikLZ5Pke9ylQ","targetId":"_E57hIYldEDikLZ5Pke9ylQ","type":"Triggering"},{"id":"_TNUuQYldEDikLZ5Pke9ylQ","sourceId":"_E57hIYldEDikLZ5Pke9ylQ","targetId":"_LYPBUYldEDikLZ5Pke9ylQ","type":"Triggering"},{"id":"_g_tgEIldEDikLZ5Pke9ylQ","sourceId":"_eEJG0YldEDikLZ5Pke9ylQ","targetId":"_WSqHgYldEDikLZ5Pke9ylQ","type":"Association"},{"id":"_hTZREoldEDikLZ5Pke9ylQ","sourceId":"_fh6FUIldEDikLZ5Pke9ylQ","targetId":"_Zoez0IldEDikLZ5Pke9ylQ","type":"Association"},{"id":"_iRfRAIldEDikLZ5Pke9ylQ","sourceId":"_WSqHgYldEDikLZ5Pke9ylQ","targetId":"_Zoez0IldEDikLZ5Pke9ylQ","type":"Triggering"},{"id":"_kh4mU4ldEDikLZ5Pke9ylQ","sourceId":"_fr2g8IlcEDikLZ5Pke9ylQ","targetId":"_WSqHgYldEDikLZ5Pke9ylQ","type":"Triggering"},{"id":"_0YxmgoldEDikLZ5Pke9ylQ","sourceId":"_Zoez0IldEDikLZ5Pke9ylQ","targetId":"_E57hIYldEDikLZ5Pke9ylQ","type":"Triggering"},{"id":"_64RZgYldEDikLZ5Pke9ylQ","sourceId":"_LYPBUYldEDikLZ5Pke9ylQ","targetId":"_HROIoIldEDikLZ5Pke9ylQ","type":"Association"},{"id":"_7V0RI4ldEDikLZ5Pke9ylQ","sourceId":"_31rLMIldEDikLZ5Pke9ylQ","targetId":"_HROIoIldEDikLZ5Pke9ylQ","type":"Association"},{"id":"_B7VzoYleEDikLZ5Pke9ylQ","sourceId":"_AMrSYIleEDikLZ5Pke9ylQ","targetId":"_HROIoIldEDikLZ5Pke9ylQ","type":"Association"},{"id":"_FO52IYleEDikLZ5Pke9ylQ","sourceId":"_LYPBUYldEDikLZ5Pke9ylQ","targetId":"_AMrSYIleEDikLZ5Pke9ylQ","type":"Triggering"},{"id":"_FyrRk4leEDikLZ5Pke9ylQ","sourceId":"_AMrSYIleEDikLZ5Pke9ylQ","targetId":"_31rLMIldEDikLZ5Pke9ylQ","type":"Triggering"},{"id":"_TlxOAYleEDikLZ5Pke9ylQ","sourceId":"_Sz5sMIleEDikLZ5Pke9ylQ","targetId":"_Nqx2QYleEDikLZ5Pke9ylQ","type":"Association"},{"id":"_U-DPk4leEDikLZ5Pke9ylQ","sourceId":"__KUvcYlbEDikLZ5Pke9ylQ","targetId":"_Nqx2QYleEDikLZ5Pke9ylQ","type":"Triggering"},{"id":"_X1gk4oleEDikLZ5Pke9ylQ","sourceId":"_31rLMIldEDikLZ5Pke9ylQ","targetId":"_Nqx2QYleEDikLZ5Pke9ylQ","type":"Triggering"},{"id":"_bqkK4oleEDikLZ5Pke9ylQ","sourceId":"_Nqx2QYleEDikLZ5Pke9ylQ","targetId":"_ZXWLEYleEDikLZ5Pke9ylQ","type":"Triggering"},{"id":"_doOKYYleEDikLZ5Pke9ylQ","sourceId":"_ca1xQYleEDikLZ5Pke9ylQ","targetId":"_ZXWLEYleEDikLZ5Pke9ylQ","type":"Association"},{"id":"_f4ZdQ4leEDikLZ5Pke9ylQ","sourceId":"_ZXWLEYleEDikLZ5Pke9ylQ","targetId":"_eX564IleEDikLZ5Pke9ylQ","type":"Triggering"},{"id":"_ggafgYleEDikLZ5Pke9ylQ","sourceId":"_ca1xQYleEDikLZ5Pke9ylQ","targetId":"_eX564IleEDikLZ5Pke9ylQ","type":"Association"},{"id":"_ljTxoIleEDikLZ5Pke9ylQ","sourceId":"_hZvbkYlbEDikLZ5Pke9ylQ","targetId":"_kZb_gYleEDikLZ5Pke9ylQ","type":"Association"},{"id":"_3XKNw4leEDikLZ5Pke9ylQ","sourceId":"_z68lkYleEDikLZ5Pke9ylQ","targetId":"_w-A6YYleEDikLZ5Pke9ylQ","type":"Association"},{"id":"_9Ot3A4leEDikLZ5Pke9ylQ","sourceId":"_HcUa0IlcEDikLZ5Pke9ylQ","targetId":"_w-A6YYleEDikLZ5Pke9ylQ","type":"Triggering"},{"id":"_DSR784lfEDikLZ5Pke9ylQ","sourceId":"_w-A6YYleEDikLZ5Pke9ylQ","targetId":"_eX564IleEDikLZ5Pke9ylQ","type":"Triggering"}],"views":[{"id":"_igamgactEeqEM7mFKilpXw","name":"archimate-diagram","viewpoint":""}]}

=== me-big-tuwien-ac-at/EAModelSet/dataset/processed-models/5a4b03f0/model.json
{"identifier":"https://me.big.tuwien.ac.at/EAModelSet/5a4b03f0","archimateId":"5a4b03f0","name":"design patterns overview","description":"","formats":["XML","CSV","JSON","ARCHIMATE"],"source":"GitHub","repository":"wilmerkrisp/patterns","license":"Other","sourceFile":"raw-data/github/archimate/design_patterns_overview.archimate","sourceFormat":"ARCHIMATE","timestamp":"2023-07-06T09:29:17","tags":[],"duplicates":[],"language":"en","elements":[{"id":"2c37c934","name":"Business Object","type":"BusinessObject","layer":"business"},{"id":"14b58684","name":"4 Prototype","type":"Grouping","layer":"other"},{"id":"2aba2a80","name":"2 Builder","type":"Grouping","layer":"other"},{"id":"a15e4522","name":"Grouping","type":"Grouping","layer":"other"},{"id":"bc97dfcc","name":"3 Factory Method","type":"Grouping","layer":"other"},{"id":"e5bb37de","name":"1 Abstract Factory","type":"Grouping","layer":"other"},{"id":"ff7a6138","name":"Grouping","type":"Grouping","layer":"other"},{"id":"35ec24d7","name":"Grouping (copy)","type":"Grouping","layer":"other"},{"id":"5d42f1f1","name":"Grouping (copy)","type":"Grouping","layer":"other"},{"id":"c752e79a","name":"Grouping (copy)","type":"Grouping","layer":"other"},{"id":"ff5ee466","name":"5 Singleton","type":"Grouping","layer":"other"},{"id":"55041cbd","name":"Grouping (copy)","type":"Grouping","layer":"other"},{"id":"f37d4261","name":"Grouping (copy)","type":"Grouping","layer":"other"},{"id":"bb4d1f5f","name":"Grouping (copy)","type":"Grouping","layer":"other"},{"id":"d054d4ac","name":"Grouping (copy)","type":"Grouping","layer":"other"},{"id":"520e2be3","name":"4 Decorator","type":"Grouping","layer":"other"},{"id":"a216642c","name":"2 Bridge","type":"Grouping","layer":"other"},{"id":"bd081a0d","name":"3 Composite","type":"Grouping","layer":"other"},{"id":"47dfd9e0","name":"1 Adapter","type":"Grouping","layer":"other"},{"id":"a928f99c","name":"Grouping (copy) (copy)","type":"Grouping","layer":"other"},{"id":"9d40ed53","name":"6 Flyweight","type":"Grouping","layer":"other"},{"id":"341804e6","name":"7 Proxy","type":"Grouping","layer":"other"},{"id":"62887790","name":"5 Facade","type":"Grouping","layer":"other"},{"id":"c26b0508","name":"Grouping (copy) (copy)","type":"Grouping","layer":"other"},{"id":"3debbd1a","name":"Grouping (copy) (copy)","type":"Grouping","layer":"other"},{"id":"0f5228aa","name":"Grouping (copy) (copy)","type":"Grouping","layer":"other"},{"id":"62fdc3e4","name":"Grouping (copy) (copy)","type":"Grouping","layer":"other"},{"id":"af704474","name":"4 Iterator","type":"Grouping","layer":"other"},{"id":"dca50c4c","name":"2 Command","type":"Grouping","layer":"other"},{"id":"2fe44a0f","name":"3 Interpreter","type":"Grouping","layer":"other"},{"id":"b4fdf0d7","name":"1 Chain of Responsibility","type":"Grouping","layer":"other"},{"id":"4143c2d3","name":"8 State","type":"Grouping","layer":"other"},{"id":"dcd14142","name":"6 Memento","type":"Grouping","layer":"other"},{"id":"9fa9cb9d","name":"7 Observer","type":"Grouping","layer":"other"},{"id":"da148b31","name":"5 Mediator","type":"Grouping","layer":"other"},{"id":"a3b7933d","name":"Grouping (copy) (copy)","type":"Grouping","layer":"other"},{"id":"89f9be7e","name":"10 Template Method","type":"Grouping","layer":"other"},{"id":"a0aeeee5","name":"11 Visitor","type":"Grouping","layer":"other"},{"id":"9680dc3c","name":"9 Strategy","type":"Grouping","layer":"other"}],"relationships":[],"views":[{"id":"4b91674a","name":"map","viewpoint":""},{"id":"3d3b7211","name":"map (template temp)","viewpoint":""}]}
