=== me-big-tuwien-ac-at/EAModelSet/schemas/ea-model.schema.json
{
  "$id": "https://me.big.tuwien.ac.at/EAModelSet/schemas/ea-model.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "EA Model Schema",
  "description": "A detailed representation of an EA Model including its elements, relationships, and views",
  "type": "object",
  "required": [
    "identifier",
    "archimateId",
    "name",
    "description",
    "formats",
    "source",
    "repository",
    "license",
    "sourceFile",
    "sourceFormat",
    "timestamp",
    "tags",
    "duplicates",
    "language",
    "elements",
    "relationships",
    "views"
  ],
  "properties": {
    "identifier": {
      "type": "string",
      "format": "uri",
      "description": "Unique URI identifier to access the model"
    },
    "archimateId": {
      "type": "string",
      "description": "ArchiMate ID from the source file of the model"
    },
    "name": {
      "type": "string",
      "description": "Name of the model"
    },
    "description": {
      "type": "string",
      "description": "Additional information about the model (e.g. description, purpose, scope)"
    },
    "formats": {
      "type": "array",
      "description": "Available, downloadable formats of the model",
      "items": {
        "type": "string",
        "enum": [ "JSON", "ARCHIMATE", "XML", "CSV", "PNG" ]
      }
    },
    "source": {
      "type": "string",
      "description": "Source where the model was downloaded from",
      "enum": [ "GitHub", "GenMyModel", "Other", "Unknown" ]
    },
    "repository": {
      "type": "string",
      "description": "Specific repository location of the source model"
    },
    "license": {
      "type": "string",
      "description": "License for the model"
    },
    "sourceFile": {
      "type": "string",
      "description": "Relative file path of the parsed model file"
    },
    "sourceFormat": {
      "type": "string",
      "description": "Source format of the original downloaded model",
      "enum": [ "ARCHIMATE", "XML" ]
    },
    "timestamp": {
      "type": "string",
      "format": "date-time"
    },
    "tags": {
      "type": "array",
      "description": "Additional tags to classify the model",
      "items": {
        "type": "string",
        "enum": [ "DUPLICATE", "WARNING" ]
      }
    },
    "duplicates": {
      "type": "array",
      "description": "Relative file path of detected duplicates (e.g. same ID)",
      "items": {
        "type": "string"
      }
    },
    "language": {
      "type": "string",
      "description": "Language of the model",
      "enum": [
        "aa", "ab", "ae", "af", "ak", "am", "an", "ar", "as", "av", "ay", "az", "ba", "be", "bg", "bi",
        "bm", "bn", "bo", "br", "bs", "ca", "ce", "ch", "co", "cr", "cs", "cu", "cv", "cy", "da", "de",
        "dv", "dz", "ee", "el", "en", "eo", "es", "et", "eu", "fa", "ff", "fi", "fj", "fo", "fr", "fy",
        "ga", "gd", "gl", "gn", "gu", "gv", "ha", "he", "hi", "ho", "hr", "ht", "hu", "hy", "hz", "ia",
        "id", "ie", "ig", "ii", "ik", "io", "is", "it", "iu", "ja", "jv", "ka", "kg", "ki", "kj", "kk",
        "kl", "km", "kn", "ko", "kr", "ks", "ku", "kv", "kw", "ky", "la", "lb", "lg", "li", "ln", "lo",
        "lt", "lu", "lv", "mg", "mh", "mi", "mk", "ml", "mn", "mr", "ms", "mt", "my", "na", "nb", "nd",
        "ne", "ng", "nl", "nn", "no", "nr", "nv", "ny", "oc", "oj", "om", "or", "os", "pa", "pi", "pl",
        "ps", "pt", "qu", "rm", "rn", "ro", "ru", "rw", "sa", "sc", "sd", "se", "sg", "sh", "si", "sk",
        "sl", "sm", "sn", "so", "sq", "sr", "ss", "st", "su", "sv", "sw", "ta", "te", "tg", "th", "ti",
        "tk", "tl", "tn", "to", "tr", "ts", "tt", "tw", "ty", "ug", "uk", "ur", "uz", "ve", "vi", "vo",
        "wa", "wo", "xh", "yi", "yo", "za", "zh", "zu"
      ]
    },
    "elements": {
      "type": "array",
      "items": { "$ref": "#/$defs/element" }
    },
    "relationships": {
      "type": "array",
      "items": { "$ref": "#/$defs/relationship" }
    },
    "views": {
      "type": "array",
      "items": { "$ref": "#/$defs/view" }
    }
  },
  "$defs": {
    "element": {
      "type": "object",
      "required": [ "id", "name", "type", "layer" ],
      "properties": {
        "id": {
          "type": "string",
          "description": "Unique identifier of the element"
        },
        "name": {
          "type": "string",
          "description": "Name of the element"
        },
        "type": {
          "type": "string",
          "description": "Type of the element"
        },
        "layer": {
          "type": "string",
          "description": "Layer of the element (computed through type)"
        }
      }
    },
    "relationship": {
      "type": "object",
      "required": [ "id", "sourceId", "targetId", "type" ],
      "properties": {
        "id": {
          "type": "string",
          "description": "Unique identifier of the element"
        },
        "sourceId": {
          "type": "string",
          "description": "ID of the source element"
        },
        "targetId": {
          "type": "string",
          "description": "ID of the target element"
        },
        "type": {
          "type": "string",
          "description": "Type of the element"
        }
      }
    },
    "view": {
      "type": "object",
      "required": [ "id", "name", "viewpoint"],
      "properties": {
        "id": {
          "type": "string",
          "description": "Unique identifier of the view"
        },
        "name": {
          "type": "string",
          "description": "Name of the element"
        },
        "viewpoint": {
          "type": "string",
          "description": "Associated viewpoint to the view (optional)"
        }
      }
    }
  }
}

=== me-big-tuwien-ac-at/EAModelSet/dataset/processed-models/_d2MGQIGDEeyiydZsM2RdLg/model.json
{"identifier":"https://me.big.tuwien.ac.at/EAModelSet/_d2MGQIGDEeyiydZsM2RdLg","archimateId":"_d2MGQIGDEeyiydZsM2RdLg","name":"Electronic Ticketing Genealogy","description":"","formats":["XML","CSV","JSON","ARCHIMATE"],"source":"GenMyModel","repository":"","license":"","sourceFile":"raw-data/genmymodel/_d2mgqigdeeyiydzsm2rdlg.xml","sourceFormat":"XML","timestamp":"2023-07-06T10:01:18","tags":[],"duplicates":[],"language":"fr","elements":[{"id":"_flbjEGOyEDqZK4-iqDQE1w","name":"Super Admin","type":"BusinessActor","layer":"business"},{"id":"_g_5V8GOyEDqZK4-iqDQE1w","name":"Admin","type":"BusinessActor","layer":"business"},{"id":"_0S-wMGOyEDqZK4-iqDQE1w","name":"DevOps","type":"BusinessActor","layer":"business"},{"id":"_7rrcEGOyEDqZK4-iqDQE1w","name":"Admin","type":"BusinessActor","layer":"business"},{"id":"_8P2gIGOyEDqZK4-iqDQE1w","name":"Admin","type":"BusinessActor","layer":"business"},{"id":"_AvYmgGOzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_Q8JwEGOzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_SpdmcGOzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_V_26gGOzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_V_26gmOzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_XPJYIGOzEDqZK4-iqDQE1w","name":"Agent","type":"BusinessActor","layer":"business"},{"id":"_XPJYImOzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_XPJYJGOzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_abjCsGOzEDqZK4-iqDQE1w","name":"Agent","type":"BusinessActor","layer":"business"},{"id":"_abjpwWOzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_abjpw2OzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_a2ui0GOzEDqZK4-iqDQE1w","name":"Agent","type":"BusinessActor","layer":"business"},{"id":"_a2ui0mOzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_a2ui1GOzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_bNom8GOzEDqZK4-iqDQE1w","name":"Agent","type":"BusinessActor","layer":"business"},{"id":"_bNom8mOzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_bNom9GOzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_bsEPYGOzEDqZK4-iqDQE1w","name":"Agent","type":"BusinessActor","layer":"business"},{"id":"_bsEPYmOzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_bsEPZGOzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_cEU-YGOzEDqZK4-iqDQE1w","name":"Agent","type":"BusinessActor","layer":"business"},{"id":"_cEU-YmOzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_cEU-ZGOzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_ceDtAGOzEDqZK4-iqDQE1w","name":"Agent","type":"BusinessActor","layer":"business"},{"id":"_ceDtAmOzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_ceDtBGOzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_c0PYYGOzEDqZK4-iqDQE1w","name":"Agent","type":"BusinessActor","layer":"business"},{"id":"_c0P_cGOzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_c0P_cmOzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_ZHidIGOzEDqZK4-iqDQE1w","name":"Agent","type":"BusinessActor","layer":"business"},{"id":"_ZHidImOzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_ZHidJGOzEDqZK4-iqDQE1w","name":"Manager","type":"BusinessActor","layer":"business"},{"id":"_mxdPcGOzEDqZK4-iqDQE1w","name":"Ticket Sales","type":"BusinessService","layer":"business"},{"id":"_YeM2IGO8EDqFW-jzZ2nkDg","name":"indipendent participants","type":"BusinessActor","layer":"business"}],"relationships":[{"id":"_ymarQGOzEDqZK4-iqDQE1w","sourceId":"_c0PYYGOzEDqZK4-iqDQE1w","targetId":"_V_26gGOzEDqZK4-iqDQE1w","type":"Serving"},{"id":"_lA9WoGO9EDqFW-jzZ2nkDg","sourceId":"_ceDtAGOzEDqZK4-iqDQE1w","targetId":"_SpdmcGOzEDqZK4-iqDQE1w","type":"Serving"},{"id":"_gKcToGO9EDqFW-jzZ2nkDg","sourceId":"_cEU-YGOzEDqZK4-iqDQE1w","targetId":"_SpdmcGOzEDqZK4-iqDQE1w","type":"Serving"},{"id":"_cnxeIGO9EDqFW-jzZ2nkDg","sourceId":"_bsEPYGOzEDqZK4-iqDQE1w","targetId":"_SpdmcGOzEDqZK4-iqDQE1w","type":"Serving"},{"id":"_iSpWQGO9EDqFW-jzZ2nkDg","sourceId":"_bNom8GOzEDqZK4-iqDQE1w","targetId":"_SpdmcGOzEDqZK4-iqDQE1w","type":"Serving"},{"id":"_vXhh0GO9EDqFW-jzZ2nkDg","sourceId":"_a2ui0GOzEDqZK4-iqDQE1w","targetId":"_Q8JwEGOzEDqZK4-iqDQE1w","type":"Serving"},{"id":"_wB1DEGO9EDqFW-jzZ2nkDg","sourceId":"_abjCsGOzEDqZK4-iqDQE1w","targetId":"_Q8JwEGOzEDqZK4-iqDQE1w","type":"Serving"},{"id":"_kBUqIGOzEDqZK4-iqDQE1w","sourceId":"_AvYmgGOzEDqZK4-iqDQE1w","targetId":"_g_5V8GOyEDqZK4-iqDQE1w","type":"Serving"},{"id":"_vRTwoGOzEDqZK4-iqDQE1w","sourceId":"_mxdPcGOzEDqZK4-iqDQE1w","targetId":"_c0PYYGOzEDqZK4-iqDQE1w","type":"Serving"},{"id":"_4zi74GOzEDqZK4-iqDQE1w","sourceId":"_mxdPcGOzEDqZK4-iqDQE1w","targetId":"_V_26gGOzEDqZK4-iqDQE1w","type":"Serving"},{"id":"_7S7vcGOzEDqZK4-iqDQE1w","sourceId":"_mxdPcGOzEDqZK4-iqDQE1w","targetId":"_8P2gIGOyEDqZK4-iqDQE1w","type":"Serving"},{"id":"_QA-EwGO0EDqnYsduVKC8Gw","sourceId":"_8P2gIGOyEDqZK4-iqDQE1w","targetId":"_flbjEGOyEDqZK4-iqDQE1w","type":"Serving"},{"id":"_vNqQoGO8EDqFW-jzZ2nkDg","sourceId":"_YeM2IGO8EDqFW-jzZ2nkDg","targetId":"_mxdPcGOzEDqZK4-iqDQE1w","type":"Flow"},{"id":"_wYGDcGO8EDqFW-jzZ2nkDg","sourceId":"_mxdPcGOzEDqZK4-iqDQE1w","targetId":"_0S-wMGOyEDqZK4-iqDQE1w","type":"Flow"},{"id":"_pWOtwGO9EDqFW-jzZ2nkDg","sourceId":"_mxdPcGOzEDqZK4-iqDQE1w","targetId":"_bsEPYGOzEDqZK4-iqDQE1w","type":"Flow"},{"id":"_qgp5gGO9EDqFW-jzZ2nkDg","sourceId":"_mxdPcGOzEDqZK4-iqDQE1w","targetId":"_cEU-YGOzEDqZK4-iqDQE1w","type":"Flow"},{"id":"_rnuPQGO9EDqFW-jzZ2nkDg","sourceId":"_mxdPcGOzEDqZK4-iqDQE1w","targetId":"_bNom8GOzEDqZK4-iqDQE1w","type":"Flow"},{"id":"_sEgR4GO9EDqFW-jzZ2nkDg","sourceId":"_mxdPcGOzEDqZK4-iqDQE1w","targetId":"_ceDtAGOzEDqZK4-iqDQE1w","type":"Flow"},{"id":"_s1jUUGO9EDqFW-jzZ2nkDg","sourceId":"_SpdmcGOzEDqZK4-iqDQE1w","targetId":"_7rrcEGOyEDqZK4-iqDQE1w","type":"Serving"},{"id":"_ukCPYGO9EDqFW-jzZ2nkDg","sourceId":"_mxdPcGOzEDqZK4-iqDQE1w","targetId":"_a2ui0GOzEDqZK4-iqDQE1w","type":"Flow"},{"id":"_xKfUQGO9EDqFW-jzZ2nkDg","sourceId":"_XPJYIGOzEDqZK4-iqDQE1w","targetId":"_AvYmgGOzEDqZK4-iqDQE1w","type":"Serving"},{"id":"_xzfN8GO9EDqFW-jzZ2nkDg","sourceId":"_ZHidIGOzEDqZK4-iqDQE1w","targetId":"_AvYmgGOzEDqZK4-iqDQE1w","type":"Serving"},{"id":"_zVwR8GO9EDqFW-jzZ2nkDg","sourceId":"_mxdPcGOzEDqZK4-iqDQE1w","targetId":"_XPJYIGOzEDqZK4-iqDQE1w","type":"Flow"},{"id":"_0NM3UGO9EDqFW-jzZ2nkDg","sourceId":"_mxdPcGOzEDqZK4-iqDQE1w","targetId":"_abjCsGOzEDqZK4-iqDQE1w","type":"Flow"},{"id":"_0zbw4GO9EDqFW-jzZ2nkDg","sourceId":"_mxdPcGOzEDqZK4-iqDQE1w","targetId":"_ZHidIGOzEDqZK4-iqDQE1w","type":"Flow"},{"id":"_6oanQGO9EDqFW-jzZ2nkDg","sourceId":"_Q8JwEGOzEDqZK4-iqDQE1w","targetId":"_g_5V8GOyEDqZK4-iqDQE1w","type":"Serving"}],"views":[{"id":"_d2MGQ4GDEeyiydZsM2RdLg","name":"archimate-diagram","viewpoint":""}]}

=== me-big-tuwien-ac-at/EAModelSet/dataset/processed-models/_AZb0kKziEe2vW5IAILnJcQ/model.json
{"identifier":"https://me.big.tuwien.ac.at/EAModelSet/_AZb0kKziEe2vW5IAILnJcQ","archimateId":"_AZb0kKziEe2vW5IAILnJcQ","name":"D1","description":"","formats":["XML","CSV","JSON","ARCHIMATE"],"source":"GenMyModel","repository":"","license":"","sourceFile":"raw-data/genmymodel/_azb0kkziee2vw5iailnjcq.xml","sourceFormat":"XML","timestamp":"2023-07-06T10:01:17","tags":[],"duplicates":[],"language":"es","elements":[{"id":"_aT4bsI8SEDuemesZNDqwog","name":"Comprador","type":"BusinessActor","layer":"business"},{"id":"_bflZ0I8SEDuemesZNDqwog","name":"S1-Abastecimiento productos","type":"BusinessService","layer":"business"},{"id":"_gcTygI8SEDuemesZNDqwog","name":"Proveedor","type":"BusinessActor","layer":"business"},{"id":"_hhX9II8SEDuemesZNDqwog","name":"Empleado","type":"BusinessActor","layer":"business"},{"id":"_x9ntII8SEDuemesZNDqwog","name":"S2-Obtener productos mediante      las tiendas físicas ","type":"BusinessService","layer":"business"},{"id":"_08R2oI8SEDuemesZNDqwog","name":"S3-Atención al cliente durante la selección de productos","type":"BusinessService","layer":"business"},{"id":"_giTa4I8UEDuemesZNDqwog","name":"Creador","type":"BusinessActor","layer":"business"},{"id":"_ib2WcI8UEDuemesZNDqwog","name":"Backer","type":"BusinessActor","layer":"business"},{"id":"_uJaJwI8UEDuemesZNDqwog","name":"Subir proyecto","type":"BusinessService","layer":"business"},{"id":"_vXftgI8UEDuemesZNDqwog","name":"Apoyar proyecto","type":"BusinessService","layer":"business"},{"id":"_WuilUI8VEDuemesZNDqwog","name":"Plataforma","type":"BusinessObject","layer":"business"},{"id":"_co1ZgI8VEDuemesZNDqwog","name":"Bien Físico o Digital","type":"BusinessObject","layer":"business"},{"id":"_xJcW0I8VEDuemesZNDqwog","name":"Productos físicos de terceros","type":"BusinessObject","layer":"business"},{"id":"_KfRWoI8WEDuemesZNDqwog","name":"Servicio: Atención al cliente ","type":"BusinessObject","layer":"business"}],"relationships":[{"id":"_AT-HoI8TEDuemesZNDqwog","sourceId":"_hhX9II8SEDuemesZNDqwog","targetId":"_08R2oI8SEDuemesZNDqwog","type":"Assignment"},{"id":"_BQyVMI8TEDuemesZNDqwog","sourceId":"_hhX9II8SEDuemesZNDqwog","targetId":"_08R2oI8SEDuemesZNDqwog","type":"Triggering"},{"id":"_DhyHcI8TEDuemesZNDqwog","sourceId":"_hhX9II8SEDuemesZNDqwog","targetId":"_08R2oI8SEDuemesZNDqwog","type":"Assignment"},{"id":"_epR5MI8TEDuemesZNDqwog","sourceId":"_aT4bsI8SEDuemesZNDqwog","targetId":"_x9ntII8SEDuemesZNDqwog","type":"Association"},{"id":"_fdngMI8TEDuemesZNDqwog","sourceId":"_aT4bsI8SEDuemesZNDqwog","targetId":"_x9ntII8SEDuemesZNDqwog","type":"Serving"},{"id":"_gXtw8I8TEDuemesZNDqwog","sourceId":"_aT4bsI8SEDuemesZNDqwog","targetId":"_x9ntII8SEDuemesZNDqwog","type":"Flow"},{"id":"_hEA2QI8TEDuemesZNDqwog","sourceId":"_aT4bsI8SEDuemesZNDqwog","targetId":"_x9ntII8SEDuemesZNDqwog","type":"Assignment"},{"id":"_kUwOQI8TEDuemesZNDqwog","sourceId":"_aT4bsI8SEDuemesZNDqwog","targetId":"_x9ntII8SEDuemesZNDqwog","type":"Realization"},{"id":"_llmyII8TEDuemesZNDqwog","sourceId":"_aT4bsI8SEDuemesZNDqwog","targetId":"_x9ntII8SEDuemesZNDqwog","type":"Realization"},{"id":"_mU3r4I8TEDuemesZNDqwog","sourceId":"_aT4bsI8SEDuemesZNDqwog","targetId":"_x9ntII8SEDuemesZNDqwog","type":"Triggering"},{"id":"_nVKEMI8TEDuemesZNDqwog","sourceId":"_aT4bsI8SEDuemesZNDqwog","targetId":"_x9ntII8SEDuemesZNDqwog","type":"Assignment"},{"id":"_qc208I8TEDuemesZNDqwog","sourceId":"_gcTygI8SEDuemesZNDqwog","targetId":"_bflZ0I8SEDuemesZNDqwog","type":"Assignment"},{"id":"_wuYA4I8UEDuemesZNDqwog","sourceId":"_giTa4I8UEDuemesZNDqwog","targetId":"_uJaJwI8UEDuemesZNDqwog","type":"Association"},{"id":"_8p8bAI8UEDuemesZNDqwog","sourceId":"_giTa4I8UEDuemesZNDqwog","targetId":"_uJaJwI8UEDuemesZNDqwog","type":"Assignment"},{"id":"_9LdMoI8UEDuemesZNDqwog","sourceId":"_ib2WcI8UEDuemesZNDqwog","targetId":"_vXftgI8UEDuemesZNDqwog","type":"Assignment"},{"id":"_cDi7II8VEDuemesZNDqwog","sourceId":"_uJaJwI8UEDuemesZNDqwog","targetId":"_WuilUI8VEDuemesZNDqwog","type":"Access"},{"id":"_hc6zkI8VEDuemesZNDqwog","sourceId":"_vXftgI8UEDuemesZNDqwog","targetId":"_co1ZgI8VEDuemesZNDqwog","type":"Association"},{"id":"_jV9Y0I8VEDuemesZNDqwog","sourceId":"_vXftgI8UEDuemesZNDqwog","targetId":"_co1ZgI8VEDuemesZNDqwog","type":"Association"},{"id":"_0NAOcI8VEDuemesZNDqwog","sourceId":"_bflZ0I8SEDuemesZNDqwog","targetId":"_xJcW0I8VEDuemesZNDqwog","type":"Association"},{"id":"_1keXsI8VEDuemesZNDqwog","sourceId":"_x9ntII8SEDuemesZNDqwog","targetId":"_xJcW0I8VEDuemesZNDqwog","type":"Association"},{"id":"_MAlYYI8WEDuemesZNDqwog","sourceId":"_08R2oI8SEDuemesZNDqwog","targetId":"_KfRWoI8WEDuemesZNDqwog","type":"Association"},{"id":"_Oh9wAI8WEDuemesZNDqwog","sourceId":"_uJaJwI8UEDuemesZNDqwog","targetId":"_WuilUI8VEDuemesZNDqwog","type":"Association"}],"views":[{"id":"_AZb0k6ziEe2vW5IAILnJcQ","name":"archimate-diagram","viewpoint":""}]}

=== me-big-tuwien-ac-at/EAModelSet/vue-website/public/processed-models/_JIuKcDklEeufTvxJgLajhw/model.json
{"identifier":"https://me.big.tuwien.ac.at/EAModelSet/_JIuKcDklEeufTvxJgLajhw","archimateId":"_JIuKcDklEeufTvxJgLajhw","name":"PAKS-II. Research and development","description":"","formats":["XML","CSV","JSON","ARCHIMATE"],"source":"GenMyModel","repository":"","license":"","sourceFile":"raw-data/genmymodel/_jiukcdkleeuftvxjglajhw.xml","sourceFormat":"XML","timestamp":"2023-07-06T10:01:17","tags":[],"duplicates":[],"language":"ru","elements":[{"id":"_IRbfUBtTEDmpCuKuMOPkqw","name":"УТ1. Разработка требований стейкхолдеров","type":"BusinessFunction","layer":"business"},{"id":"_K4K4EBtTEDmpCuKuMOPkqw","name":"Инженер по управлению требованиями","type":"BusinessRole","layer":"business"},{"id":"_NG2WIBtTEDmpCuKuMOPkqw","name":"Требования стейкхолдеров","type":"Product","layer":"business"},{"id":"_P5AUsBtTEDmpCuKuMOPkqw","name":"ОА1. Определение функциональной архитектуры","type":"BusinessFunction","layer":"business"},{"id":"_Zh_BIBtTEDmpCuKuMOPkqw","name":"Архитектор","type":"BusinessRole","layer":"business"},{"id":"_a8-YcBtTEDmpCuKuMOPkqw","name":"Функциональная диаграмма","type":"Product","layer":"business"},{"id":"_juvJABtTEDmpCuKuMOPkqw","name":"УТ2. Разработка функциональных требований","type":"BusinessFunction","layer":"business"},{"id":"_DisC0BtUEDmpCuKuMOPkqw","name":"Инженер по управлению требованиями","type":"BusinessRole","layer":"business"},{"id":"_FsnjwBtUEDmpCuKuMOPkqw","name":"Функциональные требования","type":"Product","layer":"business"},{"id":"_JYwB0BtVEDmpCuKuMOPkqw","name":"ОА2. Модульный синтез","type":"BusinessFunction","layer":"business"},{"id":"_LfFcMBtVEDmpCuKuMOPkqw","name":"УТ3. Разработка технических требований","type":"BusinessFunction","layer":"business"},{"id":"_Wpk-sBtVEDmpCuKuMOPkqw","name":"Структурная диаграмма","type":"Product","layer":"business"},{"id":"_08wCQBtVEDmpCuKuMOPkqw","name":"Технические требования","type":"Product","layer":"business"}],"relationships":[{"id":"_Mi5UgBtTEDmpCuKuMOPkqw","sourceId":"_K4K4EBtTEDmpCuKuMOPkqw","targetId":"_IRbfUBtTEDmpCuKuMOPkqw","type":"Association"},{"id":"_PPtgEBtTEDmpCuKuMOPkqw","sourceId":"_IRbfUBtTEDmpCuKuMOPkqw","targetId":"_NG2WIBtTEDmpCuKuMOPkqw","type":"Association"},{"id":"_aoSh4BtTEDmpCuKuMOPkqw","sourceId":"_Zh_BIBtTEDmpCuKuMOPkqw","targetId":"_P5AUsBtTEDmpCuKuMOPkqw","type":"Association"},{"id":"_dpNVMBtTEDmpCuKuMOPkqw","sourceId":"_P5AUsBtTEDmpCuKuMOPkqw","targetId":"_a8-YcBtTEDmpCuKuMOPkqw","type":"Association"},{"id":"_eQrvcBtUEDmpCuKuMOPkqw","sourceId":"_juvJABtTEDmpCuKuMOPkqw","targetId":"_DisC0BtUEDmpCuKuMOPkqw","type":"Association"},{"id":"_ewB94BtUEDmpCuKuMOPkqw","sourceId":"_juvJABtTEDmpCuKuMOPkqw","targetId":"_FsnjwBtUEDmpCuKuMOPkqw","type":"Association"},{"id":"_-uO_4BtUEDmpCuKuMOPkqw","sourceId":"_NG2WIBtTEDmpCuKuMOPkqw","targetId":"_P5AUsBtTEDmpCuKuMOPkqw","type":"Flow"},{"id":"_A38eYBtVEDmpCuKuMOPkqw","sourceId":"_NG2WIBtTEDmpCuKuMOPkqw","targetId":"_juvJABtTEDmpCuKuMOPkqw","type":"Flow"},{"id":"_CVjr4BtVEDmpCuKuMOPkqw","sourceId":"_a8-YcBtTEDmpCuKuMOPkqw","targetId":"_juvJABtTEDmpCuKuMOPkqw","type":"Flow"},{"id":"_Pxsg4BtVEDmpCuKuMOPkqw","sourceId":"_a8-YcBtTEDmpCuKuMOPkqw","targetId":"_JYwB0BtVEDmpCuKuMOPkqw","type":"Flow"},{"id":"_Rk1ScBtVEDmpCuKuMOPkqw","sourceId":"_NG2WIBtTEDmpCuKuMOPkqw","targetId":"_LfFcMBtVEDmpCuKuMOPkqw","type":"Flow"},{"id":"_fBazYBtVEDmpCuKuMOPkqw","sourceId":"_Zh_BIBtTEDmpCuKuMOPkqw","targetId":"_JYwB0BtVEDmpCuKuMOPkqw","type":"Association"},{"id":"_f_HKsBtVEDmpCuKuMOPkqw","sourceId":"_JYwB0BtVEDmpCuKuMOPkqw","targetId":"_Wpk-sBtVEDmpCuKuMOPkqw","type":"Association"},{"id":"_grIjMBtVEDmpCuKuMOPkqw","sourceId":"_Wpk-sBtVEDmpCuKuMOPkqw","targetId":"_LfFcMBtVEDmpCuKuMOPkqw","type":"Flow"},{"id":"_4WygMBtVEDmpCuKuMOPkqw","sourceId":"_DisC0BtUEDmpCuKuMOPkqw","targetId":"_LfFcMBtVEDmpCuKuMOPkqw","type":"Association"},{"id":"_6V208BtVEDmpCuKuMOPkqw","sourceId":"_08wCQBtVEDmpCuKuMOPkqw","targetId":"_LfFcMBtVEDmpCuKuMOPkqw","type":"Association"},{"id":"_7nqbEBtVEDmpCuKuMOPkqw","sourceId":"_FsnjwBtUEDmpCuKuMOPkqw","targetId":"_LfFcMBtVEDmpCuKuMOPkqw","type":"Flow"}],"views":[{"id":"_JIuxgjklEeufTvxJgLajhw","name":"archimate-diagram","viewpoint":""}]}

=== me-big-tuwien-ac-at/EAModelSet/dataset/processed-models/f5eee014-861f-40fe-922e-fe24bfd562c7/model.json
{"identifier":"https://me.big.tuwien.ac.at/EAModelSet/f5eee014-861f-40fe-922e-fe24bfd562c7","archimateId":"f5eee014-861f-40fe-922e-fe24bfd562c7","name":"Esquema","description":"","formats":["XML","CSV","JSON","ARCHIMATE"],"source":"GenMyModel","repository":"","license":"","sourceFile":"raw-data/genmymodel/f5eee014-861f-40fe-922e-fe24bfd562c7.xml","sourceFormat":"XML","timestamp":"2023-07-06T10:01:18","tags":[],"duplicates":[],"language":"es","elements":[{"id":"_HAxLALUPEDaaVc4rj22kRw","name":"PLAN DE TRABAJO","type":"BusinessService","layer":"business"},{"id":"_Nia6IbUPEDaaVc4rj22kRw","name":"PLAN DE TRABAJO","type":"TechnologyService","layer":"technology"},{"id":"_P3f7IbUPEDaaVc4rj22kRw","name":"MARKETING","type":"TechnologyService","layer":"technology"},{"id":"_dnm1AbUPEDaaVc4rj22kRw","name":"Desarrolla una investigación de mercado","type":"ApplicationService","layer":"application"},{"id":"_eTOk4bUPEDaaVc4rj22kRw","name":"Elabora ánalisis de la competencia","type":"ApplicationService","layer":"application"},{"id":"_fbvFEbUPEDaaVc4rj22kRw","name":"Estudios de mercado","type":"ApplicationService","layer":"application"},{"id":"_Ot8j0NI0EDa6P43StyjgDw","name":"PRODUCCION","type":"TechnologyService","layer":"technology"},{"id":"_QNE0QNI0EDa6P43StyjgDw","name":"ORGANIZACION","type":"TechnologyService","layer":"technology"},{"id":"_RMoz0NI0EDa6P43StyjgDw","name":"ASPECTOS LEGALES DE IMPLANTACION Y OPERACION","type":"TechnologyService","layer":"technology"},{"id":"_Uxy8oNI0EDa6P43StyjgDw","name":"FINANZAS","type":"TechnologyService","layer":"technology"},{"id":"_XiYN4NI0EDa6P43StyjgDw","name":"INTEGRACION DE ACTIVIDADES","type":"TechnologyService","layer":"technology"},{"id":"_guKoANI0EDa6P43StyjgDw","name":"Establece el sistema de distribucción","type":"ApplicationService","layer":"application"},{"id":"_m45E4NI0EDa6P43StyjgDw","name":"Diseño de empaque","type":"ApplicationService","layer":"application"},{"id":"_cw5EsNI1EDa6P43StyjgDw","name":"Publicidad de la empresa","type":"ApplicationService","layer":"application"},{"id":"_foKz0NI1EDa6P43StyjgDw","name":"Diseño, etiquetas, anuncios, nombre comercial","type":"ApplicationService","layer":"application"},{"id":"_f3lI0NI1EDa6P43StyjgDw","name":"Define sistema de promoción","type":"ApplicationService","layer":"application"},{"id":"_fSfh8NI5EDa6P43StyjgDw","name":"Metas","type":"WorkPackage","layer":"implementation_migration"},{"id":"_YxmLUNI6EDaLK_908QdQtw","name":"Asignar tiempos","type":"WorkPackage","layer":"implementation_migration"},{"id":"_ZGVsQNI6EDaLK_908QdQtw","name":"Responsabilidades","type":"WorkPackage","layer":"implementation_migration"},{"id":"_ZntT8NI6EDaLK_908QdQtw","name":"Recursos","type":"WorkPackage","layer":"implementation_migration"}],"relationships":[{"id":"_W07AQLUPEDaaVc4rj22kRw","sourceId":"_HAxLALUPEDaaVc4rj22kRw","targetId":"_Nia6IbUPEDaaVc4rj22kRw","type":"Triggering"},{"id":"_XZfs8rUPEDaaVc4rj22kRw","sourceId":"_HAxLALUPEDaaVc4rj22kRw","targetId":"_P3f7IbUPEDaaVc4rj22kRw","type":"Triggering"},{"id":"_qNCWMNI0EDa6P43StyjgDw","sourceId":"_HAxLALUPEDaaVc4rj22kRw","targetId":"_Ot8j0NI0EDa6P43StyjgDw","type":"Triggering"},{"id":"_t0lrsNI0EDa6P43StyjgDw","sourceId":"_HAxLALUPEDaaVc4rj22kRw","targetId":"_QNE0QNI0EDa6P43StyjgDw","type":"Triggering"},{"id":"_xhrBcNI0EDa6P43StyjgDw","sourceId":"_HAxLALUPEDaaVc4rj22kRw","targetId":"_RMoz0NI0EDa6P43StyjgDw","type":"Triggering"},{"id":"_0uZcINI0EDa6P43StyjgDw","sourceId":"_HAxLALUPEDaaVc4rj22kRw","targetId":"_XiYN4NI0EDa6P43StyjgDw","type":"Triggering"},{"id":"_12LjkNI0EDa6P43StyjgDw","sourceId":"_HAxLALUPEDaaVc4rj22kRw","targetId":"_Uxy8oNI0EDa6P43StyjgDw","type":"Triggering"},{"id":"_tO_ZYNI2EDa6P43StyjgDw","sourceId":"_dnm1AbUPEDaaVc4rj22kRw","targetId":"_eTOk4bUPEDaaVc4rj22kRw","type":"Composition"},{"id":"_vW0BgNI2EDa6P43StyjgDw","sourceId":"_dnm1AbUPEDaaVc4rj22kRw","targetId":"_eTOk4bUPEDaaVc4rj22kRw","type":"Association"},{"id":"_zGYDgdI2EDa6P43StyjgDw","sourceId":"_eTOk4bUPEDaaVc4rj22kRw","targetId":"_fbvFEbUPEDaaVc4rj22kRw","type":"Association"},{"id":"_0IK3sNI2EDa6P43StyjgDw","sourceId":"_fbvFEbUPEDaaVc4rj22kRw","targetId":"_guKoANI0EDa6P43StyjgDw","type":"Association"},{"id":"_078eAdI2EDa6P43StyjgDw","sourceId":"_guKoANI0EDa6P43StyjgDw","targetId":"_cw5EsNI1EDa6P43StyjgDw","type":"Association"},{"id":"_2o9ZcNI2EDa6P43StyjgDw","sourceId":"_cw5EsNI1EDa6P43StyjgDw","targetId":"_foKz0NI1EDa6P43StyjgDw","type":"Association"},{"id":"_3wozMdI2EDa6P43StyjgDw","sourceId":"_foKz0NI1EDa6P43StyjgDw","targetId":"_f3lI0NI1EDa6P43StyjgDw","type":"Association"},{"id":"_4vWeMNI2EDa6P43StyjgDw","sourceId":"_f3lI0NI1EDa6P43StyjgDw","targetId":"_m45E4NI0EDa6P43StyjgDw","type":"Association"},{"id":"_X0S1kNI6EDaLK_908QdQtw","sourceId":"_P3f7IbUPEDaaVc4rj22kRw","targetId":"_dnm1AbUPEDaaVc4rj22kRw","type":"Association"},{"id":"_Y9EJkNI8EDaLK_908QdQtw","sourceId":"_Nia6IbUPEDaaVc4rj22kRw","targetId":"_YxmLUNI6EDaLK_908QdQtw","type":"Association"},{"id":"_cMLw8dI8EDaLK_908QdQtw","sourceId":"_YxmLUNI6EDaLK_908QdQtw","targetId":"_ZGVsQNI6EDaLK_908QdQtw","type":"Association"},{"id":"_gg6VgNI8EDaLK_908QdQtw","sourceId":"_ZGVsQNI6EDaLK_908QdQtw","targetId":"_fSfh8NI5EDa6P43StyjgDw","type":"Association"},{"id":"_iCL7ANI8EDaLK_908QdQtw","sourceId":"_fSfh8NI5EDa6P43StyjgDw","targetId":"_ZntT8NI6EDaLK_908QdQtw","type":"Association"}],"views":[{"id":"_LxrBctLgEeiczqJWtOPN4Q","name":"Esquema","viewpoint":""},{"id":"_FxI1UNI-EDaLK_908QdQtw","name":"archimate-diagram","viewpoint":""},{"id":"_GKqIkNI-EDaLK_908QdQtw","name":"archimate-diagram2","viewpoint":""},{"id":"_Gp-h0dI-EDaLK_908QdQtw","name":"archimate-diagram3","viewpoint":""},{"id":"_HR1MANI-EDaLK_908QdQtw","name":"archimate-diagram4","viewpoint":""}]}
