=== me-big-tuwien-ac-at/EAModelSet/schemas/ea-model.schema.json
{
  "$id": "https://me.big.tuwien.ac.at/EAModelSet/schemas/ea-model.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "EA Model Schema",
  "description": "A detailed representation of an EA Model including its elements, relationships, and views",
  "type": "object",
  "required": [
    "identifier",
    "archimateId",
    "name",
    "description",
    "formats",
    "source",
    "repository",
    "license",
    "sourceFile",
    "sourceFormat",
    "timestamp",
    "tags",
    "duplicates",
    "language",
    "elements",
    "relationships",
    "views"
  ],
  "properties": {
    "identifier": {
      "type": "string",
      "format": "uri",
      "description": "Unique URI identifier to access the model"
    },
    "archimateId": {
      "type": "string",
      "description": "ArchiMate ID from the source file of the model"
    },
    "name": {
      "type": "string",
      "description": "Name of the model"
    },
    "description": {
      "type": "string",
      "description": "Additional information about the model (e.g. description, purpose, scope)"
    },
    "formats": {
      "type": "array",
      "description": "Available, downloadable formats of the model",
      "items": {
        "type": "string",
        "enum": [ "JSON", "ARCHIMATE", "XML", "CSV", "PNG" ]
      }
    },
    "source": {
      "type": "string",
      "description": "Source where the model was downloaded from",
      "enum": [ "GitHub", "GenMyModel", "Other", "Unknown" ]
    },
    "repository": {
      "type": "string",
      "description": "Specific repository location of the source model"
    },
    "license": {
      "type": "string",
      "description": "License for the model"
    },
    "sourceFile": {
      "type": "string",
      "description": "Relative file path of the parsed model file"
    },
    "sourceFormat": {
      "type": "string",
      "description": "Source format of the original downloaded model",
      "enum": [ "ARCHIMATE", "XML" ]
    },
    "timestamp": {
      "type": "string",
      "format": "date-time"
    },
    "tags": {
      "type": "array",
      "description": "Additional tags to classify the model",
      "items": {
        "type": "string",
        "enum": [ "DUPLICATE", "WARNING" ]
      }
    },
    "duplicates": {
      "type": "array",
      "description": "Relative file path of detected duplicates (e.g. same ID)",
      "items": {
        "type": "string"
      }
    },
    "language": {
      "type": "string",
      "description": "Language of the model",
      "enum": [
        "aa", "ab", "ae", "af", "ak", "am", "an", "ar", "as", "av", "ay", "az", "ba", "be", "bg", "bi",
        "bm", "bn", "bo", "br", "bs", "ca", "ce", "ch", "co", "cr", "cs", "cu", "cv", "cy", "da", "de",
        "dv", "dz", "ee", "el", "en", "eo", "es", "et", "eu", "fa", "ff", "fi", "fj", "fo", "fr", "fy",
        "ga", "gd", "gl", "gn", "gu", "gv", "ha", "he", "hi", "ho", "hr", "ht", "hu", "hy", "hz", "ia",
        "id", "ie", "ig", "ii", "ik", "io", "is", "it", "iu", "ja", "jv", "ka", "kg", "ki", "kj", "kk",
        "kl", "km", "kn", "ko", "kr", "ks", "ku", "kv", "kw", "ky", "la", "lb", "lg", "li", "ln", "lo",
        "lt", "lu", "lv", "mg", "mh", "mi", "mk", "ml", "mn", "mr", "ms", "mt", "my", "na", "nb", "nd",
        "ne", "ng", "nl", "nn", "no", "nr", "nv", "ny", "oc", "oj", "om", "or", "os", "pa", "pi", "pl",
        "ps", "pt", "qu", "rm", "rn", "ro", "ru", "rw", "sa", "sc", "sd", "se", "sg", "sh", "si", "sk",
        "sl", "sm", "sn", "so", "sq", "sr", "ss", "st", "su", "sv", "sw", "ta", "te", "tg", "th", "ti",
        "tk", "tl", "tn", "to", "tr", "ts", "tt", "tw", "ty", "ug", "uk", "ur", "uz", "ve", "vi", "vo",
        "wa", "wo", "xh", "yi", "yo", "za", "zh", "zu"
      ]
    },
    "elements": {
      "type": "array",
      "items": { "$ref": "#/$defs/element" }
    },
    "relationships": {
      "type": "array",
      "items": { "$ref": "#/$defs/relationship" }
    },
    "views": {
      "type": "array",
      "items": { "$ref": "#/$defs/view" }
    }
  },
  "$defs": {
    "element": {
      "type": "object",
      "required": [ "id", "name", "type", "layer" ],
      "properties": {
        "id": {
          "type": "string",
          "description": "Unique identifier of the element"
        },
        "name": {
          "type": "string",
          "description": "Name of the element"
        },
        "type": {
          "type": "string",
          "description": "Type of the element"
        },
        "layer": {
          "type": "string",
          "description": "Layer of the element (computed through type)"
        }
      }
    },
    "relationship": {
      "type": "object",
      "required": [ "id", "sourceId", "targetId", "type" ],
      "properties": {
        "id": {
          "type": "string",
          "description": "Unique identifier of the element"
        },
        "sourceId": {
          "type": "string",
          "description": "ID of the source element"
        },
        "targetId": {
          "type": "string",
          "description": "ID of the target element"
        },
        "type": {
          "type": "string",
          "description": "Type of the element"
        }
      }
    },
    "view": {
      "type": "object",
      "required": [ "id", "name", "viewpoint"],
      "properties": {
        "id": {
          "type": "string",
          "description": "Unique identifier of the view"
        },
        "name": {
          "type": "string",
          "description": "Name of the element"
        },
        "viewpoint": {
          "type": "string",
          "description": "Associated viewpoint to the view (optional)"
        }
      }
    }
  }
}

=== me-big-tuwien-ac-at/EAModelSet/vue-website/public/processed-models/id-363d5e2d641f4975acd4fe60a0c5a2fb/model.json
{"identifier":"https://me.big.tuwien.ac.at/EAModelSet/id-363d5e2d641f4975acd4fe60a0c5a2fb","archimateId":"id-363d5e2d641f4975acd4fe60a0c5a2fb","name":"heeus-ce-se","description":"","formats":["ARCHIMATE","XML","CSV","JSON"],"source":"GitHub","repository":"voedger/voedger","license":"MIT","sourceFile":"raw-data/github/archimate/heeus.archimate","sourceFormat":"ARCHIMATE","timestamp":"2024-02-21T01:38:16","tags":[],"duplicates":[],"language":"en","elements":[{"id":"id-08da35c089fb42f3b805cf5b9b111814","name":"HTTPProcessor","type":"TechnologyFunction","layer":"technology"},{"id":"id-d3e9b849ef934dbbb2b540e228e3f331","name":"HTTPProcessorController","type":"TechnologyFunction","layer":"technology"},{"id":"id-6a47fe3512f042ca98eb9e40eb3e545b","name":"cluster","type":"Artifact","layer":"technology"},{"id":"id-d7d1b8a1d3d647babe0caa44b908fbf0","name":"AppPartitions","type":"TechnologyFunction","layer":"technology"},{"id":"id-545fa4146ae245f5b2244df4e2fc6415","name":"AppPartition","type":"TechnologyFunction","layer":"technology"},{"id":"id-17a9dd37c5f146b78899870b1772f14b","name":"QueryProcessor","type":"TechnologyFunction","layer":"technology"},{"id":"id-e2f59ee5210b481595fa1743e47f30fd","name":"CommandProcessor","type":"TechnologyFunction","layer":"technology"},{"id":"id-50306169ace4429ebf634e7389077ca3","name":"AppPartitionsController","type":"TechnologyFunction","layer":"technology"},{"id":"id-798e7ed8c4894facb1313a89f8b5a38d","name":"FederationGateway","type":"TechnologyFunction","layer":"technology"},{"id":"id-cac88d766fd94952b2a9919c52c42634","name":"HTTPGateway","type":"TechnologyFunction","layer":"technology"},{"id":"id-46193ddd2c104b67a85ad1cbdf2991aa","name":"MailerGateway","type":"TechnologyFunction","layer":"technology"},{"id":"id-d4253bdffd944edab1776ccad52006ec","name":"IBus","type":"TechnologyFunction","layer":"technology"},{"id":"id-bdb15d498edc4925b82026c1bac1fe9d","name":"HTTPProcessorSender","type":"Path","layer":"technology"},{"id":"id-6b40a0d9184d41dc871a10406f33920d","name":"<owner>/<app>/c","type":"Path","layer":"technology"},{"id":"id-8a2d289ba1184b108bfa07e23fb63a10","name":"<owner>/<app>/q","type":"Path","layer":"technology"},{"id":"id-a1df316fc27e4c3ab1c6f667780ac4c4","name":"FederationGatewaySender","type":"Path","layer":"technology"},{"id":"id-a6db6eec345747bb991243a342164388","name":"HTTPGatewaySender","type":"Path","layer":"technology"},{"id":"id-4aba940b14d345e5800235142a188634","name":"MailerGatewaySender","type":"Path","layer":"technology"},{"id":"id-95d564172dcb4f82863d0359fd8a60e4","name":"Projector","type":"TechnologyFunction","layer":"technology"},{"id":"id-3643150b94644546b7cf8ecf7781f1a1","name":"FederationGatewayProcessor","type":"TechnologyFunction","layer":"technology"},{"id":"id-cf6edb9e5b644482bdb1a7893b95450e","name":"HTTPGatewayProcessor","type":"TechnologyFunction","layer":"technology"},{"id":"id-e199771eb7df49739c41af3be8150b62","name":"MailerGatewayProcessor","type":"TechnologyFunction","layer":"technology"},{"id":"id-c2098a0c528142088e989fb3dbd3872e","name":"Exporters/Importers","type":"Grouping","layer":"other"}],"relationships":[{"id":"id-3be8a0f10a0240feb9be9b2334d86fa9","sourceId":"id-d3e9b849ef934dbbb2b540e228e3f331","targetId":"id-08da35c089fb42f3b805cf5b9b111814","type":"Flow"},{"id":"id-5b8bfcdf9c5f4cb5bf5faa740a0f3e97","sourceId":"id-d3e9b849ef934dbbb2b540e228e3f331","targetId":"id-6a47fe3512f042ca98eb9e40eb3e545b","type":"Access"},{"id":"id-a4fde8bfcfc84fc98842743bc50b6798","sourceId":"id-d7d1b8a1d3d647babe0caa44b908fbf0","targetId":"id-545fa4146ae245f5b2244df4e2fc6415","type":"Aggregation"},{"id":"id-08a8046e267e4aedb094409b39793039","sourceId":"id-545fa4146ae245f5b2244df4e2fc6415","targetId":"id-e2f59ee5210b481595fa1743e47f30fd","type":"Aggregation"},{"id":"id-a8dc799e3f0f4eca8a5fb853f06c1f68","sourceId":"id-545fa4146ae245f5b2244df4e2fc6415","targetId":"id-17a9dd37c5f146b78899870b1772f14b","type":"Aggregation"},{"id":"id-e0918c19b68b4bb6ab477fddd963edd7","sourceId":"id-50306169ace4429ebf634e7389077ca3","targetId":"id-d7d1b8a1d3d647babe0caa44b908fbf0","type":"Flow"},{"id":"id-b9f70eeab48c4d47891ee4cc40afb750","sourceId":"id-50306169ace4429ebf634e7389077ca3","targetId":"id-6a47fe3512f042ca98eb9e40eb3e545b","type":"Access"},{"id":"id-5c90f8c16cea41d68e62d3e33d7b3972","sourceId":"id-d3e9b849ef934dbbb2b540e228e3f331","targetId":"id-bdb15d498edc4925b82026c1bac1fe9d","type":"Flow"},{"id":"id-82e71c34809e4bd9b686e05ddd7bb5ef","sourceId":"id-bdb15d498edc4925b82026c1bac1fe9d","targetId":"id-08da35c089fb42f3b805cf5b9b111814","type":"Flow"},{"id":"id-47e8fa7dd2b54ac69c1a77826cf51085","sourceId":"id-08da35c089fb42f3b805cf5b9b111814","targetId":"id-6b40a0d9184d41dc871a10406f33920d","type":"Flow"},{"id":"id-633361e014b6481b8d44edc568feb23a","sourceId":"id-08da35c089fb42f3b805cf5b9b111814","targetId":"id-8a2d289ba1184b108bfa07e23fb63a10","type":"Flow"},{"id":"id-fb2d126cfb1c44d185f757a228739b8a","sourceId":"id-6b40a0d9184d41dc871a10406f33920d","targetId":"id-e2f59ee5210b481595fa1743e47f30fd","type":"Flow"},{"id":"id-b6a4e1b6abe149f49233f6a530d4eb99","sourceId":"id-8a2d289ba1184b108bfa07e23fb63a10","targetId":"id-17a9dd37c5f146b78899870b1772f14b","type":"Flow"},{"id":"id-21a6a286e15849e2b3a518e36e3ae68b","sourceId":"id-d4253bdffd944edab1776ccad52006ec","targetId":"id-17a9dd37c5f146b78899870b1772f14b","type":"Serving"},{"id":"id-a9222e6b66fe4d18b02128afe04fbf92","sourceId":"id-545fa4146ae245f5b2244df4e2fc6415","targetId":"id-d4253bdffd944edab1776ccad52006ec","type":"Flow"},{"id":"id-f5587d87b66045cf98dce1aac343746c","sourceId":"id-d4253bdffd944edab1776ccad52006ec","targetId":"id-bdb15d498edc4925b82026c1bac1fe9d","type":"Association"},{"id":"id-2721060fbbc34d26a8d8332d59b6625d","sourceId":"id-d4253bdffd944edab1776ccad52006ec","targetId":"id-8a2d289ba1184b108bfa07e23fb63a10","type":"Association"},{"id":"id-bb747500cee7404599f4a93ae9ad82c3","sourceId":"id-d4253bdffd944edab1776ccad52006ec","targetId":"id-6b40a0d9184d41dc871a10406f33920d","type":"Association"},{"id":"id-4ce6c1bbebf74f6ca2167155cb4a849a","sourceId":"id-a1df316fc27e4c3ab1c6f667780ac4c4","targetId":"id-798e7ed8c4894facb1313a89f8b5a38d","type":"Flow"},{"id":"id-0d2a9d094c464c9eb39d71efe307a394","sourceId":"id-a6db6eec345747bb991243a342164388","targetId":"id-cac88d766fd94952b2a9919c52c42634","type":"Flow"},{"id":"id-a622c60fb33c4706a32702c9c36e30d8","sourceId":"id-4aba940b14d345e5800235142a188634","targetId":"id-46193ddd2c104b67a85ad1cbdf2991aa","type":"Flow"},{"id":"id-19eaa67639eb4b9fa16862532d6bf125","sourceId":"id-c2098a0c528142088e989fb3dbd3872e","targetId":"id-17a9dd37c5f146b78899870b1772f14b","type":"Aggregation"},{"id":"id-755bc720231f4c98b79f0d23dd696acd","sourceId":"id-c2098a0c528142088e989fb3dbd3872e","targetId":"id-a1df316fc27e4c3ab1c6f667780ac4c4","type":"Flow"},{"id":"id-e248c0da4d7949b28058584484278423","sourceId":"id-c2098a0c528142088e989fb3dbd3872e","targetId":"id-a6db6eec345747bb991243a342164388","type":"Flow"},{"id":"id-1fc35c65c3e7453ea99832b20e1f2154","sourceId":"id-c2098a0c528142088e989fb3dbd3872e","targetId":"id-4aba940b14d345e5800235142a188634","type":"Flow"},{"id":"id-d888131eda0e463b8da39a1d18fd2619","sourceId":"id-545fa4146ae245f5b2244df4e2fc6415","targetId":"id-95d564172dcb4f82863d0359fd8a60e4","type":"Aggregation"},{"id":"id-457135c4a8ed4dd1871bdfa76f7d4ec0","sourceId":"id-c2098a0c528142088e989fb3dbd3872e","targetId":"id-95d564172dcb4f82863d0359fd8a60e4","type":"Aggregation"},{"id":"id-9356cd8f81774e6ba265b4b853b4b9a4","sourceId":"id-798e7ed8c4894facb1313a89f8b5a38d","targetId":"id-3643150b94644546b7cf8ecf7781f1a1","type":"Composition"},{"id":"id-08a6c7104e2d4670aa5a054442d2ae87","sourceId":"id-cac88d766fd94952b2a9919c52c42634","targetId":"id-cf6edb9e5b644482bdb1a7893b95450e","type":"Composition"},{"id":"id-240f5d024ca14ea89c8fc75f3ced82e0","sourceId":"id-46193ddd2c104b67a85ad1cbdf2991aa","targetId":"id-e199771eb7df49739c41af3be8150b62","type":"Composition"}],"views":[{"id":"id-7702051add304ddbb8c0118d47e29cc1","name":"00-Processors & Gateways","viewpoint":""},{"id":"id-4b0fd28edfb343959fcdaba46273b69a","name":"z-Bookmarks","viewpoint":""},{"id":"id-f1b95ed73583436596cdb84a8c1dd3a9","name":"20-HTTPProcessor & Bus","viewpoint":""},{"id":"id-55391af1cc22490290ae0f179fe5919e","name":"30-Gateways & Bus","viewpoint":""}]}

=== me-big-tuwien-ac-at/EAModelSet/vue-website/public/processed-models/_ay028PGjEeqygJczXaaxEQ/model.json
{"identifier":"https://me.big.tuwien.ac.at/EAModelSet/_ay028PGjEeqygJczXaaxEQ","archimateId":"_ay028PGjEeqygJczXaaxEQ","name":"payments-arch","description":"","formats":["XML","CSV","JSON","ARCHIMATE"],"source":"GenMyModel","repository":"","license":"","sourceFile":"raw-data/genmymodel/_ay028pgjeeqygjczxaaxeq.xml","sourceFormat":"XML","timestamp":"2023-07-06T10:01:17","tags":[],"duplicates":[],"language":"en","elements":[{"id":"_nntn8NPREDiUdI4HmtuzBA","name":"WebForm Custom","type":"ApplicationService","layer":"application"},{"id":"_tJ9IgNPREDiUdI4HmtuzBA","name":"WebHook Public Node","type":"ApplicationService","layer":"application"},{"id":"_7kHE8NPREDiUdI4HmtuzBA","name":"CloudPayments","type":"ApplicationService","layer":"application"},{"id":"_9wT2wNPREDiUdI4HmtuzBA","name":"others","type":"ApplicationService","layer":"application"},{"id":"_NZlRsNPSEDiUdI4HmtuzBA","name":"Software","type":"SystemSoftware","layer":"technology"},{"id":"_OrvdINPSEDiUdI4HmtuzBA","name":"Collaboration","type":"BusinessCollaboration","layer":"business"},{"id":"_Qzw5kNPSEDiUdI4HmtuzBA","name":"Event Pub\\Sub Bus","type":"SystemSoftware","layer":"technology"},{"id":"_YGh8kNPSEDiUdI4HmtuzBA","name":"App","type":"ApplicationService","layer":"application"},{"id":"_lszlANPSEDiUdI4HmtuzBA","name":"General Store","type":"TechnologyCollaboration","layer":"technology"},{"id":"_pYxgcNPSEDiUdI4HmtuzBA","name":"Internal Store","type":"TechnologyCollaboration","layer":"technology"},{"id":"_sg350NPSEDiUdI4HmtuzBA","name":"Collaboration","type":"TechnologyCollaboration","layer":"technology"},{"id":"_u3o84NPSEDiUdI4HmtuzBA","name":"Core Service","type":"ApplicationService","layer":"application"},{"id":"_wp2hYNPSEDiUdI4HmtuzBA","name":"Internal store","type":"TechnologyCollaboration","layer":"technology"},{"id":"_0a8NYNPSEDiUdI4HmtuzBA","name":"Http Adapter service","type":"ApplicationService","layer":"application"},{"id":"_FHK6INPTEDiUdI4HmtuzBA","name":"Api Adapter service","type":"ApplicationService","layer":"application"},{"id":"_LzyjINPTEDiUdI4HmtuzBA","name":"Event Bus Adapter","type":"ApplicationService","layer":"application"},{"id":"_1q9uANPWEDiUdI4HmtuzBA","name":"Service","type":"ApplicationService","layer":"application"},{"id":"_3Q-CgNPWEDiUdI4HmtuzBA","name":"Http Form Service","type":"ApplicationService","layer":"application"}],"relationships":[{"id":"_EbQr0NPSEDiUdI4HmtuzBA","sourceId":"_7kHE8NPREDiUdI4HmtuzBA","targetId":"_tJ9IgNPREDiUdI4HmtuzBA","type":"Serving"},{"id":"_2hXHUNPSEDiUdI4HmtuzBA","sourceId":"_tJ9IgNPREDiUdI4HmtuzBA","targetId":"_0a8NYNPSEDiUdI4HmtuzBA","type":"Serving"},{"id":"_27I5QNPSEDiUdI4HmtuzBA","sourceId":"_nntn8NPREDiUdI4HmtuzBA","targetId":"_0a8NYNPSEDiUdI4HmtuzBA","type":"Serving"},{"id":"_3r_HYNPSEDiUdI4HmtuzBA","sourceId":"_0a8NYNPSEDiUdI4HmtuzBA","targetId":"_u3o84NPSEDiUdI4HmtuzBA","type":"Serving"},{"id":"_4xn5wNPSEDiUdI4HmtuzBA","sourceId":"_u3o84NPSEDiUdI4HmtuzBA","targetId":"_0a8NYNPSEDiUdI4HmtuzBA","type":"Serving"},{"id":"_7SwZwNPSEDiUdI4HmtuzBA","sourceId":"_0a8NYNPSEDiUdI4HmtuzBA","targetId":"_nntn8NPREDiUdI4HmtuzBA","type":"Serving"},{"id":"___pmsNPSEDiUdI4HmtuzBA","sourceId":"_u3o84NPSEDiUdI4HmtuzBA","targetId":"_wp2hYNPSEDiUdI4HmtuzBA","type":"Serving"},{"id":"_AeT4oNPTEDiUdI4HmtuzBA","sourceId":"_wp2hYNPSEDiUdI4HmtuzBA","targetId":"_u3o84NPSEDiUdI4HmtuzBA","type":"Serving"},{"id":"_B1qtINPTEDiUdI4HmtuzBA","sourceId":"_u3o84NPSEDiUdI4HmtuzBA","targetId":"_lszlANPSEDiUdI4HmtuzBA","type":"Serving"},{"id":"_CTMWoNPTEDiUdI4HmtuzBA","sourceId":"_lszlANPSEDiUdI4HmtuzBA","targetId":"_u3o84NPSEDiUdI4HmtuzBA","type":"Serving"},{"id":"_GkeloNPTEDiUdI4HmtuzBA","sourceId":"_YGh8kNPSEDiUdI4HmtuzBA","targetId":"_FHK6INPTEDiUdI4HmtuzBA","type":"Serving"},{"id":"_H1apENPTEDiUdI4HmtuzBA","sourceId":"_FHK6INPTEDiUdI4HmtuzBA","targetId":"_YGh8kNPSEDiUdI4HmtuzBA","type":"Serving"},{"id":"_JDjQINPTEDiUdI4HmtuzBA","sourceId":"_FHK6INPTEDiUdI4HmtuzBA","targetId":"_u3o84NPSEDiUdI4HmtuzBA","type":"Serving"},{"id":"_Jb9JENPTEDiUdI4HmtuzBA","sourceId":"_u3o84NPSEDiUdI4HmtuzBA","targetId":"_FHK6INPTEDiUdI4HmtuzBA","type":"Serving"},{"id":"_NyIfINPTEDiUdI4HmtuzBA","sourceId":"_u3o84NPSEDiUdI4HmtuzBA","targetId":"_LzyjINPTEDiUdI4HmtuzBA","type":"Serving"},{"id":"_ONEHoNPTEDiUdI4HmtuzBA","sourceId":"_LzyjINPTEDiUdI4HmtuzBA","targetId":"_Qzw5kNPSEDiUdI4HmtuzBA","type":"Serving"},{"id":"_fBKW8NPTEDiUdI4HmtuzBA","sourceId":"_Qzw5kNPSEDiUdI4HmtuzBA","targetId":"_YGh8kNPSEDiUdI4HmtuzBA","type":"Serving"},{"id":"_zRYH0NPTEDiUdI4HmtuzBA","sourceId":"_u3o84NPSEDiUdI4HmtuzBA","targetId":"_7kHE8NPREDiUdI4HmtuzBA","type":"Serving"},{"id":"_8Ey94NPWEDiUdI4HmtuzBA","sourceId":"_nntn8NPREDiUdI4HmtuzBA","targetId":"_3Q-CgNPWEDiUdI4HmtuzBA","type":"Serving"},{"id":"_8mcSYNPWEDiUdI4HmtuzBA","sourceId":"_3Q-CgNPWEDiUdI4HmtuzBA","targetId":"_u3o84NPSEDiUdI4HmtuzBA","type":"Serving"}],"views":[{"id":"_ay028_GjEeqygJczXaaxEQ","name":"archimate-diagram","viewpoint":""}]}

=== me-big-tuwien-ac-at/EAModelSet/dataset/processed-models/1d703f78/model.json
{"identifier":"https://me.big.tuwien.ac.at/EAModelSet/1d703f78","archimateId":"1d703f78","name":"everything","description":"\n# Purpose\n\nThis **ArchiMate** Model is here to illustrate the abilty to use [Markdown](https://daringfireball.net/projects/markdown/)\nfor markup in *Documentation* tags.\n\n* lists\n* lists\n* lists\n\nYou also include code examples:\n\n    // Code examples\n    while (true) {\n      this.burnCpu();\n    }\n\n  ","formats":["XML","CSV","JSON","ARCHIMATE"],"source":"GitHub","repository":"mmorga/archimate-diff","license":"Apache License 2.0","sourceFile":"raw-data/github/archimate/everything.archimate","sourceFormat":"ARCHIMATE","timestamp":"2023-07-06T09:29:17","tags":["WARNING"],"duplicates":[],"language":"en","elements":[{"id":"895b5ec5","name":"Business Actor","type":"BusinessActor","layer":"business"},{"id":"d1a45f58","name":"Business Role","type":"BusinessRole","layer":"business"},{"id":"b6677ae1","name":"Business Collaboration","type":"BusinessCollaboration","layer":"business"},{"id":"bc1ceb46","name":"Business Interface","type":"BusinessInterface","layer":"business"},{"id":"15e2172c","name":"Business Function","type":"BusinessFunction","layer":"business"},{"id":"70630355","name":"Business Process","type":"BusinessProcess","layer":"business"},{"id":"cfffd652","name":"Business Event","type":"BusinessEvent","layer":"business"},{"id":"2a00fdf3","name":"Business Interaction","type":"BusinessInteraction","layer":"business"},{"id":"f0090d70","name":"Product","type":"Product","layer":"business"},{"id":"03064f37","name":"Contract","type":"Contract","layer":"business"},{"id":"b5dd94c9","name":"Business Service","type":"BusinessService","layer":"business"},{"id":"ab4c4726","name":"Representation of us and all of that","type":"Representation","layer":"business"},{"id":"e1616652","name":"Business Object","type":"BusinessObject","layer":"business"},{"id":"11af7615","name":"Business Interface","type":"BusinessInterface","layer":"business"},{"id":"d393c534","name":"Business Process","type":"BusinessProcess","layer":"business"},{"id":"495250a2","name":"Business Service","type":"BusinessService","layer":"business"},{"id":"f123a9d3","name":"Business Actor","type":"BusinessActor","layer":"business"},{"id":"e7c1a5f3","name":"Business Process","type":"BusinessProcess","layer":"business"},{"id":"867c2f22","name":"Business Process","type":"BusinessProcess","layer":"business"},{"id":"890c6b06","name":"Business Event hello red fish blue fish","type":"BusinessEvent","layer":"business"},{"id":"4e337ab3","name":"Application Component","type":"ApplicationComponent","layer":"application"},{"id":"a3965597","name":"Application Collaboration","type":"ApplicationCollaboration","layer":"application"},{"id":"72abc76d","name":"Application Interface","type":"ApplicationInterface","layer":"application"},{"id":"e5504f30","name":"Application Service","type":"ApplicationService","layer":"application"},{"id":"9b0af2d9","name":"Application Function","type":"ApplicationFunction","layer":"application"},{"id":"51eecad7","name":"Application Interaction","type":"ApplicationInteraction","layer":"application"},{"id":"75a63568","name":"Data Object","type":"DataObject","layer":"application"},{"id":"2f331587","name":"Application Component","type":"ApplicationComponent","layer":"application"},{"id":"8b0269a0","name":"Application Interface","type":"ApplicationInterface","layer":"application"},{"id":"c50ea139","name":"Application Service","type":"ApplicationService","layer":"application"},{"id":"0fd56a64-8ee7-4777-93e3-2fd4ae66fe2b","name":"Application Event","type":"ApplicationEvent","layer":"application"},{"id":"1c8c458d-7c1a-4424-b3bd-ff236bd9888b","name":"Application Process","type":"ApplicationProcess","layer":"application"},{"id":"a58c2cff","name":"Artifact that I found one day","type":"Artifact","layer":"technology"},{"id":"61b2ebb6","name":"Communication Path","type":"Path","layer":"technology"},{"id":"b55b532f","name":"Network","type":"CommunicationNetwork","layer":"technology"},{"id":"f5bb4733","name":"Infrastructure Interface","type":"TechnologyInterface","layer":"technology"},{"id":"c3b8630a","name":"Infrastructure Function","type":"TechnologyFunction","layer":"technology"},{"id":"1637e896","name":"Infrastructure Service","type":"TechnologyService","layer":"technology"},{"id":"7eacfc0f","name":"Node","type":"Node","layer":"technology"},{"id":"5d63c4ac","name":"System Software","type":"SystemSoftware","layer":"technology"},{"id":"78f8493b","name":"Device","type":"Device","layer":"technology"},{"id":"7d72249a","name":"Infrastructure Interface","type":"TechnologyInterface","layer":"technology"},{"id":"a11b9eb7","name":"Infrastructure Service","type":"TechnologyService","layer":"technology"},{"id":"fa48c0eb","name":"Node","type":"Node","layer":"technology"},{"id":"89d89ded","name":"Device","type":"Device","layer":"technology"},{"id":"1ef2b6b0","name":"Stakeholder","type":"Stakeholder","layer":"motivation"},{"id":"49f1b964","name":"Driver","type":"Driver","layer":"motivation"},{"id":"21876b7e","name":"Assessment","type":"Assessment","layer":"motivation"},{"id":"35d27705","name":"Goal","type":"Goal","layer":"motivation"},{"id":"4a1a1a71","name":"Principle","type":"Principle","layer":"motivation"},{"id":"529a4b14","name":"Requirement","type":"Requirement","layer":"motivation"},{"id":"da7394bd","name":"Constraint","type":"Constraint","layer":"motivation"},{"id":"5ce14ef5","name":"Value of some thing","type":"Value","layer":"motivation"},{"id":"b9d8f495","name":"Meaning","type":"Meaning","layer":"motivation"},{"id":"77fa0664","name":"Work Package","type":"WorkPackage","layer":"implementation_migration"},{"id":"0e8739c2","name":"Deliverable","type":"Deliverable","layer":"implementation_migration"},{"id":"d89ba03a","name":"Plateau","type":"Plateau","layer":"implementation_migration"},{"id":"9005d244","name":"Gap","type":"Gap","layer":"implementation_migration"},{"id":"1bbf9386","name":"Junction","type":"Junction","layer":"other"},{"id":"2b5667ad","name":"And Junction","type":"Junction","layer":"other"},{"id":"a3344375","name":"Or Junction","type":"Junction","layer":"other"},{"id":"d8440883","name":"Location","type":"Location","layer":"other"},{"id":"5f48a3fc-7864-4e9e-ac2b-3f6f1e6a0344","name":"Grouping","type":"Grouping","layer":"other"}],"relationships":[{"id":"56731509","sourceId":"21876b7e","targetId":"35d27705","type":"Influence"},{"id":"4e16546f","sourceId":"fa48c0eb","targetId":"7eacfc0f","type":"Specialization"},{"id":"c8c82c51","sourceId":"495250a2","targetId":"b5dd94c9","type":"Composition"},{"id":"c8a3de09","sourceId":"11af7615","targetId":"bc1ceb46","type":"Aggregation"},{"id":"060a4402","sourceId":"895b5ec5","targetId":"d1a45f58","type":"Assignment"},{"id":"c181b0c6","sourceId":"15e2172c","targetId":"b5dd94c9","type":"Realization"},{"id":"065064e2","sourceId":"cfffd652","targetId":"2a00fdf3","type":"Triggering"},{"id":"43c00467","sourceId":"2a00fdf3","targetId":"a3965597","type":"Flow"},{"id":"d1290848","sourceId":"61b2ebb6","targetId":"b55b532f","type":"Association"},{"id":"277e36e1","sourceId":"15e2172c","targetId":"03064f37","type":"Access"},{"id":"03bc5201","sourceId":"4e337ab3","targetId":"e5504f30","type":"Serving"},{"id":"d9cb9327","sourceId":"70630355","targetId":"1bbf9386","type":"Flow"},{"id":"2111dd5e","sourceId":"1bbf9386","targetId":"d393c534","type":"Flow"},{"id":"6e0561fa","sourceId":"70630355","targetId":"a3344375","type":"Flow"},{"id":"6f36fe71","sourceId":"a3344375","targetId":"e7c1a5f3","type":"Flow"},{"id":"0f76942c","sourceId":"a3344375","targetId":"867c2f22","type":"Flow"},{"id":"1a162973","sourceId":"e7c1a5f3","targetId":"2b5667ad","type":"Flow"},{"id":"06a30a60","sourceId":"1bbf9386","targetId":"867c2f22","type":"Flow"},{"id":"1316e37d","sourceId":"867c2f22","targetId":"2b5667ad","type":"Flow"},{"id":"17250bc3","sourceId":"2b5667ad","targetId":"890c6b06","type":"Triggering"},{"id":"01497e63-4bef-4e9b-b6b2-2b5af4852d34","sourceId":"5f48a3fc-7864-4e9e-ac2b-3f6f1e6a0344","targetId":"5ce14ef5","type":"Composition"}],"views":[{"id":"3b1325ab","name":"Everything","viewpoint":""},{"id":"e0d837de-1ad4-4677-9112-fedf0d46aa07","name":"Referenced By Everything","viewpoint":""}]}
